const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'..'),out=root+'/artifacts/milestone7';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));const version=JSON.parse(fs.readFileSync(root+'/package.json')).version;await p.goto('file://'+root+'/downloads/Test-and-Practice-Studio-v'+version+'.html');await p.waitForSelector('#connection-topic');
const rect='course-1-en:authored:M7-perimeter-rectangle',quad='course-87-en:authored:M7-perimeter-irregular';await p.selectOption('#bank','course-1-en');await p.check('#engine-only');await p.fill('#search','M7 Perimeter rectangle');await p.locator('#questions').getByRole('button',{name:'Preview',exact:true}).click();await p.locator('#preview').getByRole('button',{name:'Find related tasks'}).click();assert.equal(await p.locator('#connection-origin').inputValue(),rect);await p.selectOption('#connection-relation','harder');await p.selectOption('#connection-bank','course-87-en');const card=p.locator('.connection-card[data-source-id='+JSON.stringify(quad)+']');assert(await card.isVisible());assert((await card.innerText()).includes('Grade 5'));await card.getByRole('button',{name:'Preview',exact:true}).click();assert((await p.locator('#engine-question').innerText()).includes('irregular quadrilateral'));assert.equal(await p.locator('#connection-origin').inputValue(),rect);await card.getByRole('button',{name:'Add to draft',exact:true}).click();await p.locator('#connection-context').getByRole('button',{name:'Add starting task'}).click();assert.equal(await p.locator('#draft-count').innerText(),'2');
await card.getByRole('button',{name:'Use as starting task'}).click();await p.selectOption('#connection-relation','easier');await p.selectOption('#connection-bank','course-1-en');const down=p.locator('.connection-card[data-source-id='+JSON.stringify(rect)+']');assert(await down.isVisible());await down.getByRole('button',{name:'Remove',exact:true}).click();assert.equal(await p.locator('#draft-count').innerText(),'1');await p.click('#undo');assert.equal(await p.locator('#draft-count').innerText(),'2');
// Preview keeps the originating comparison; relation filters never alter selections.
await p.evaluate(()=>StudioConnections.open('course-87-en:authored:MCADA-7.1'));await p.selectOption('#connection-relation','harder');assert.equal(await p.locator('.connection-card').count(),0);assert((await p.locator('#connection-status').innerText()).includes('No reviewed'));await p.fill('#connection-search','no-such-topic-zz');assert.equal(await p.locator('#connection-origin option').count(),0);await p.fill('#connection-search','');
const extras=await p.evaluate(()=>{const want=[['structured-curriculum87','93.1'],['structured-algebra-one','equation:parentheses'],['structured-algebra-two','quadratic:complex-formula'],['structured-algebra-half','binary:add'],['structured-foundational-courses','fraction-unlike'],['structured-algebra-two-completion','gas:scientific-pressure'],['structured-algebra-one','boxplot:draw'],['structured-algebra-two-completion','proof:pythagoras']];return want.map(([family,recipe])=>MathEngineBanks.catalog.find(c=>c.family===family&&c.recipe===recipe&&!c.reuseSourceId).sourceId);});
for(const id of extras){await p.evaluate(id=>StudioConnections.open(id),id);await p.locator('#connection-context').getByRole('button',{name:'Preview starting task'}).click();assert(await p.locator('#engine-question').isVisible());await p.locator('#connection-context').getByRole('button',{name:'Add starting task'}).click();}
assert.equal(await p.locator('#draft-count').innerText(),'10');await p.evaluate(()=>StudioConnections.open('course-87-en:authored:MCADA-19.1'));await p.selectOption('#connection-relation','shared-provider');assert(await p.locator('.connection-card').count()>0);await p.locator('.connection-card').first().getByRole('button',{name:'Add to draft',exact:true}).click();await p.locator('#connection-context').getByRole('button',{name:'Add starting task'}).click();assert((await p.locator('#cross-overlap-note').innerText()).includes('reuse the same provider'));assert.equal(await p.locator('#draft-count').innerText(),'12');
// Keep the exact mixed-bank draft as a replay fixture.
const dl=await Promise.all([p.waitForEvent('download'),p.click('#download')]);await dl[0].saveAs(out+'/mixed-bank-draft.json');const draft=JSON.parse(fs.readFileSync(out+'/mixed-bank-draft.json'));assert.equal(draft.itemIds.length,12);assert(new Set(draft.itemIds.map(id=>id.split(':')[0])).size>=5);
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:out+'/mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:1000});await p.evaluate(id=>StudioConnections.open(id),rect);await p.selectOption('#connection-relation','harder');await p.selectOption('#connection-bank','course-87-en');await p.locator('#connections').screenshot({path:out+'/connections.png'});
await p.fill('#packet-count','1');await p.click('#packet-manual');await p.waitForFunction(()=>!document.querySelector('#packet-print').disabled);const f=p.frames()[1];assert.equal(await f.locator('.packet-question').count(),12);assert.equal(await f.locator('.answer').count(),0);
const exports=[];for(const [paper,columns,mode]of [['A4',1,'student'],['Letter',2,'key']]){const result=await p.evaluate(async({ids,paper,columns,mode})=>{const items=ids.map(sourceId=>({sourceId,index:4})),batch=StudioPacketCore.generate([{name:'Cross-course review',items}],{title:'Mathematics practice',paper,columns,space:20,seed:'milestone7-export',footer:'Show your work',dividers:true});const reopened=StudioPacketCore.open(StudioPacketCore.record(batch));if(JSON.stringify(StudioPacketCore.record(reopened))!==JSON.stringify(StudioPacketCore.record(batch)))throw Error('replay');await StudioPackets.layout(document.querySelector('#packet-frame').contentDocument,batch,mode);const blob=await StudioPacketIO.docx(batch,mode),bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(const x of bytes)binary+=String.fromCharCode(x);return{docx:btoa(binary),html:document.querySelector('#packet-frame').contentDocument.documentElement.outerHTML,pages:document.querySelector('#packet-frame').contentDocument.querySelectorAll('.sheet').length};},{ids:draft.itemIds,paper,columns,mode});const name=paper+'-'+mode;fs.writeFileSync(out+'/'+name+'.docx',Buffer.from(result.docx,'base64'));const page=await b.newPage();await page.setContent(result.html);assert.equal(await page.locator('.answer').count(),mode==='student'?0:12);await page.pdf({path:out+'/'+name+'.pdf',preferCSSPageSize:true,printBackground:true});await page.close();exports.push({name,pages:result.pages});}
assert.deepEqual(errors,[]);const result={result:'passed',version,selected:draft.itemIds.length,banks:new Set(draft.itemIds.map(id=>id.split(':')[0])).size,exports,browser:b.version(),checks:'Exact download; perimeter upward/downward; confirmed Grade 5 label; preview without changing comparison origin; mixed-bank add/remove/undo; empty/unranked filters; shared-provider warning; draft download; packet/session replay; narrow viewport; actual Word/PDF exports'};fs.writeFileSync(out+'/browser-results.json',JSON.stringify(result,null,2));console.log(result);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
