const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('../vendor/course-banks');
(async()=>{const root=path.resolve(__dirname,'..');fs.mkdirSync(root+'/artifacts/phase3',{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox'],headless:true});const page=await browser.newPage({viewport:{width:1400,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+root+'/index.html');await page.waitForSelector('#packet-manual');await page.selectOption('#bank','course-87-en');
 const ids=['6.2','24.2','37.2','40.4','67.1','80.1','INV4.6','INV4.3'].map(x=>'course-87-en:authored:MCADA-'+x);
 for(const id of ids){await page.fill('#search',id.split(':').pop());await page.locator('input[id='+JSON.stringify('item-'+id)+']').check();}
 await page.fill('#packet-count','1');await page.fill('#packet-title','Phase 3 synthetic practice');await page.fill('#packet-footer','Show your work');await page.click('#packet-manual');await page.waitForFunction(()=>!document.querySelector('#packet-print').disabled);const frame=page.frames()[1];assert.equal(await frame.locator('.packet-question').count(),8);assert.equal(await frame.locator('.answer').count(),0);await frame.locator('.sheet').first().screenshot({path:root+'/artifacts/phase3/student-page.png'});
 const [session]=await Promise.all([page.waitForEvent('download'),page.click('#packet-save')]);await session.saveAs(root+'/artifacts/phase3/session.json');
 const [word]=await Promise.all([page.waitForEvent('download'),page.click('#packet-word')]);await word.saveAs(root+'/artifacts/phase3/student.docx');
 const pdfPage=await browser.newPage();await pdfPage.setContent(await frame.content());await pdfPage.pdf({path:root+'/artifacts/phase3/student.pdf',preferCSSPageSize:true,printBackground:true});await pdfPage.close();
 await page.selectOption('#packet-mode','key');await page.waitForFunction(()=>!document.querySelector('#packet-word').disabled);assert.equal(await frame.locator('.answer').count(),8);const [key]=await Promise.all([page.waitForEvent('download'),page.click('#packet-word')]);await key.saveAs(root+'/artifacts/phase3/key.docx');await frame.locator('.sheet').first().screenshot({path:root+'/artifacts/phase3/key-page.png'});
 await page.locator('.targeting>summary').click();const c=E.assessment.outcomes.filter(x=>x.standard);const csv='Student By Standard\nName,ID,GradeCam ID,'+c[0].alias+','+c[1].standard+',PS.MAT.G6.1.1\nSynthetic A,001,01,0,-,0.5\nSynthetic B,002,02,0.8,,0.5';await page.setInputFiles('#gradecam-file',{name:'fixture.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.waitForFunction(()=>document.querySelector('#target-students').children.length===2);await page.click('#target-review');assert.match(await page.locator('#packet-status').innerText(),/acknowledge/);await page.check('#unknown-ack');await page.check('#target-missing');await page.click('#target-review');assert.equal(await page.locator('#target-plan details').count(),2);await page.click('#target-build');await page.waitForFunction(()=>document.querySelector('#packet-list').children.length===2&&!document.querySelector('#packet-word').disabled);assert.equal(await frame.locator('.sheet').count(),2);
 // Unknown numeric scale rejected without replacing class.
 await page.setInputFiles('#gradecam-file',{name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from(csv.replace('0.8','80'))});await page.waitForFunction(()=>document.querySelector('#packet-status').textContent.includes('scale'));assert.equal(await page.locator('#target-students>div').count(),2);
 page.once('dialog',d=>d.dismiss());await page.click('#packet-clear');assert.equal(await page.locator('#packet-list>div').count(),2);page.once('dialog',d=>d.accept());await page.click('#packet-clear');assert.equal(await page.locator('#packet-list>div').count(),0);await page.click('#packet-undo');assert.equal(await page.locator('#packet-list>div').count(),2);
 // Reopen preserved exact manual session.
 page.once('dialog',d=>d.accept());await page.setInputFiles('#packet-open',root+'/artifacts/phase3/session.json');await page.waitForFunction(()=>document.querySelector('#packet-list').children.length===1);await page.selectOption('#packet-mode','student');await page.waitForFunction(()=>!document.querySelector('#packet-print').disabled);assert.equal(await frame.locator('.packet-question').count(),8);
 const original=JSON.parse(fs.readFileSync(root+'/artifacts/phase3/session.json'));const replay=await page.evaluate(d=>StudioPacketCore.record(StudioPacketCore.open(d)),original);delete original.appVersion;assert.deepEqual(replay,original);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'passed',browser:browser.version(),manualQuestions:8,batchStudents:2,checks:'student/key isolation, CSV targeting, unknown review, scale preservation, clear/cancel/undo, session replay, Word and PDF export'}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
