(async function(){'use strict';
const $=id=>document.getElementById(id),C=StudioCore,el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let catalog,banks,itemMap,lessonMaps,bankId,lessonId='',query='',page=0,previewId=null,draft={title:'My practice draft',purpose:'practice',itemIds:[],generation:{seed:'practice',indices:{}}},undo=null,dirty=false,loaded=new Map(),busy=false;
const PAGE=40,engineMap=new Map(MathEngineBanks.catalog.map(c=>[c.sourceId,c]));
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function snapshot(){return JSON.parse(JSON.stringify(draft));}
function change(fn){const before=snapshot();fn();if(JSON.stringify(before)!==JSON.stringify(draft)){undo=before;dirty=true;}renderQuestions();renderDraft();}
function bank(){return banks.get(bankId);}
function lessonLabel(i){const l=lessonMaps.get(i.bankId).get(i.lessonId);return l?.display||'Lesson not linked';}
function itemLabel(i){return engineMap.get(i.id)?.title||i.title||i.sourceId;}
function draftRecord(){return {format:'studio-manual-draft',version:2,appVersion:C.VERSION,catalog:C.CATALOG,...snapshot()};}
function add(ids){const next=[...new Set([...draft.itemIds,...ids])];if(next.length>C.MAX){status('A draft can contain up to '+C.MAX+' questions. Choose a smaller lesson or selection.',true);return;}change(()=>{draft.itemIds=next;});status(next.length+' questions in your draft.');}
function remove(ids){const set=new Set(ids);change(()=>{draft.itemIds=draft.itemIds.filter(id=>!set.has(id));});}
function setBank(){bankId=$('bank').value;lessonId='';query='';page=0;$('search').value='';$('lesson').replaceChildren(el('option','All lessons'));$('lesson').firstChild.value='';for(const l of bank().lessons){const opt=el('option',l.display+' · '+l.count);opt.value=l.id;$('lesson').append(opt);}previewId=null;renderPreview();renderQuestions();renderDraft();$('bank-info').textContent=bank().items.length.toLocaleString()+' indexed questions. '+(loaded.has(bankId)?'Source content loaded for inspection.':'Load recovered content to inspect question wording.');}
function filtered(){return bank().items.filter(i=>(!$('engine-only').checked||engineMap.has(i.id))&&(!lessonId||i.lessonId===lessonId)&&(!query||(i.sourceId+' '+itemLabel(i)+' '+lessonLabel(i)+' '+(loaded.get(bankId)?.get(i.id)?.searchText||'')).toLocaleLowerCase().includes(query)));}
function showPreview(id){previewId=id;renderPreview();renderQuestions();}
function button(label,fn,disabled=false){const b=el('button',label);b.type='button';b.disabled=disabled;b.addEventListener('click',fn);return b;}
function renderQuestions(){if(!bankId)return;const focusId=document.activeElement?.id;const all=filtered();page=Math.max(0,Math.min(page,Math.ceil(all.length/PAGE)-1));$('results').textContent=all.length.toLocaleString()+' matches';$('questions').replaceChildren();const selected=new Set(draft.itemIds);
for(const i of all.slice(page*PAGE,(page+1)*PAGE)){const row=el('div',undefined,'question-row'+(i.id===previewId?' active':''));const input=el('input');input.type='checkbox';input.checked=selected.has(i.id);input.id='item-'+i.id;input.setAttribute('aria-label','Select '+i.sourceId);input.addEventListener('change',()=>{if(input.checked)add([i.id]);else remove([i.id]);});const label=el('label');label.htmlFor=input.id;label.append(el('strong',itemLabel(i)),el('small',lessonLabel(i)),el('small',i.sourceId+' · '+(engineMap.has(i.id)?'Engine variant available':loaded.get(bankId)?.has(i.id)?'Source preview available':'Content not loaded')));row.append(input,label,button('Preview',()=>showPreview(i.id)));$('questions').append(row);}
if(!all.length)$('questions').append(el('p','No questions match. Try another lesson or search term.','empty'));
$('page-label').textContent=all.length?'Page '+(page+1)+' of '+Math.ceil(all.length/PAGE):'No results';$('previous').disabled=page===0;$('next').disabled=(page+1)*PAGE>=all.length;$('add-lesson').disabled=!lessonId||!bank().items.some(i=>i.lessonId===lessonId);if(focusId?.startsWith('item-'))document.getElementById(focusId)?.focus({preventScroll:true});}
function renderPreview(){const p=$('preview');p.replaceChildren();if(!previewId){p.append(el('p','Choose “Preview” beside a question to inspect its source content and recovery status.','empty'));return;}const i=itemMap.get(previewId),b=banks.get(i.bankId),content=loaded.get(i.bankId)?.get(i.id);p.append(el('h3',i.sourceId),el('p',b.display+' · '+lessonLabel(i),'muted'));p.append(button(draft.itemIds.includes(i.id)?'Remove from draft':'Add to draft',()=>{if(draft.itemIds.includes(i.id))remove([i.id]);else add([i.id]);renderPreview();}));
if(engineMap.has(i.id)){renderEngine(p,i);return;}
p.append(el('div','Incomplete source preview — equations, positioned diagrams, table layout, and font styling may be missing. Do not use this view as a student question.','preview-warning'));
if(!content){p.append(el('p','Question content is not loaded. Use “Load recovered content” and choose '+i.bankId+'.json from the extracted recovery package.','empty'));return;}
p.append(el('p',content.dynamic?'Dynamic template: source variables have not been evaluated.':'Source text recovered; visual and mathematical review is still required.','muted'),el('h4','Question wording'),el('div',content.prompt||'[No readable question text recovered]','source-text'));
if(content.choices.length){p.append(el('h4',content.choiceConventionUnverified?'Source choices · correct choice unverified':'Answer choices'));const list=el('ul',undefined,'source-choices');for(const c of content.choices)list.append(el('li',c.label+'. '+c.text));p.append(list);}
const details=el('details',undefined,'teacher-key');details.append(el('summary','Teacher answer • source evidence'));details.append(el('p',content.choiceConventionUnverified?'The correct-choice convention has not been verified for this generator item. Source order is preserved.':'Recovered answer association; this is not a full correctness or rendering certification.'));if(content.choiceKey)details.append(el('p','Source key: '+content.choiceKey.toUpperCase()));if(content.answer)details.append(el('div',content.answer,'source-text'));p.append(details);}
function renderEngine(p,i){
const E=MathEngineBanks,q=E.generate(i.id,{seed:draft.generation.seed,index:draft.generation.indices[i.id]||0});
p.append(el('div','Live Math Engine variant · original source-informed adaptation. This is not a reproduction of the legacy question layout.','engine-note'));
const seedLabel=el('label','Variant seed'),seed=el('input');seed.value=draft.generation.seed;seed.maxLength=200;seed.id='variant-seed';seedLabel.htmlFor=seed.id;seed.addEventListener('change',()=>{if(!seed.value.trim()){status('Enter a nonempty seed; the previous variant is preserved.',true);seed.value=draft.generation.seed;return;}change(()=>{draft.generation.seed=seed.value;});});p.append(seedLabel,seed,button('Next variant',()=>change(()=>{draft.generation.indices[i.id]=(draft.generation.indices[i.id]||0)+1;})),el('p','Variant '+q.index+' · '+E.version,'muted'));
const question=el('div');question.id='engine-question';question.innerHTML=E.renderQuestion(q);p.append(question);
const label=el('label','Try an answer'),input=el('input'),feedback=el('p');input.id='engine-response';label.htmlFor=input.id;feedback.id='engine-feedback';feedback.setAttribute('role','status');p.append(label,input,button('Check answer',()=>{feedback.textContent=E.checkAnswer(q,input.value).answerCorrect?'Correct.':'Check your answer and the requested format.';}),feedback);
const details=el('details',undefined,'teacher-key');details.append(el('summary','Teacher answer and worked solution'),el('p',E.answerText(q)),el('p',q.solution));p.append(details);
}
function renderDraft(){const list=$('draft');list.replaceChildren();$('draft-count').textContent=draft.itemIds.length;$('draft-empty').hidden=!!draft.itemIds.length;$('download').disabled=!draft.itemIds.length;$('clear').disabled=!draft.itemIds.length;$('clear-bank').disabled=!draft.itemIds.some(id=>itemMap.get(id).bankId===bankId);$('undo').disabled=!undo;
for(const [n,id]of draft.itemIds.entries()){const i=itemMap.get(id),li=el('li'),row=el('div'),label=el('div',undefined,'draft-label');label.append(el('strong',i.sourceId),el('small',banks.get(i.bankId).display+' · '+lessonLabel(i)));const actions=el('div',undefined,'actions');actions.append(button('Preview',()=>{showPreview(id);$('preview-heading').scrollIntoView({behavior:'smooth',block:'start'});}),button('↑',()=>move(n,-1),n===0),button('↓',()=>move(n,1),n===draft.itemIds.length-1),button('Remove',()=>remove([id])));actions.children[1].setAttribute('aria-label','Move '+i.sourceId+' up');actions.children[2].setAttribute('aria-label','Move '+i.sourceId+' down');row.append(label,actions);li.append(row);list.append(li);}
if(previewId)renderPreview();}
function move(n,delta){change(()=>{const [id]=draft.itemIds.splice(n,1);draft.itemIds.splice(n+delta,0,id);});}
function syncDraftFields(){$('draft-title').value=draft.title;$('purpose').value=draft.purpose;}
function hashBuffer(buf){return crypto.subtle.digest('SHA-256',buf).then(h=>Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join(''));}
async function loadContent(files){if(busy)return;busy=true;$('content-files').disabled=true;status('Checking recovered content…');try{if(!files.length)return;if(files.length>6)throw Error('Choose up to six English course JSON files.');const pending=new Map();for(const file of files){if(file.size>20*1024*1024)throw Error(file.name+' is too large. Choose a English course JSON from the recovery package.');const buf=await file.arrayBuffer(),digest=await hashBuffer(buf);const entry=Object.entries(catalog.contentHashes).find(([,h])=>h===digest);if(!entry)throw Error(file.name+' does not match the saved recovery package. Existing content and your draft are unchanged.');const [id]=entry;if(pending.has(id))throw Error('The same bank was selected more than once.');const d=JSON.parse(new TextDecoder().decode(buf));pending.set(id,C.normalizeContent(d,banks.get(id)));}
for(const [id,records]of pending)loaded.set(id,records);$('forget-content').disabled=!loaded.size;$('bank-info').textContent=bank().items.length.toLocaleString()+' indexed questions. '+(loaded.has(bankId)?'Source content loaded for inspection.':'Content not loaded for this bank.');renderQuestions();renderPreview();status('Loaded '+pending.size+' bank(s) for source inspection. Your draft is unchanged.');}catch(e){status(e.message,true);}finally{busy=false;$('content-files').disabled=false;$('content-files').value='';}}
async function openDraft(file){if(!file)return;try{if(file.size>500000)throw Error('This draft file is too large.');const next=C.validateDraft(JSON.parse(await file.text()),itemMap);if(draft.itemIds.length&&!confirm('Replace the current draft of '+draft.itemIds.length+' questions? You can undo this change. Download it first if you want a separate backup.'))return;change(()=>{draft=next;});syncDraftFields();status('Opened '+draft.itemIds.length+' selected questions. Source content must be loaded separately for previews.');}catch(e){status(e.message,true);}finally{$('draft-file').value='';}}
try{const raw=Uint8Array.from(atob($('catalog-data').textContent.trim()),c=>c.charCodeAt(0));catalog=await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'))).json();banks=new Map(catalog.banks.map(b=>[b.id,b]));itemMap=new Map();lessonMaps=new Map();for(const b of banks.values()){lessonMaps.set(b.id,new Map(b.lessons.map(l=>[l.id,l])));for(const i of b.items)itemMap.set(i.id,i);const o=el('option',b.display);o.value=b.id;$('bank').append(o);}for(const id of ['bank','lesson','search'])$(id).disabled=false;
$('engine-only').addEventListener('change',()=>{page=0;renderQuestions();});$('bank').addEventListener('change',setBank);$('lesson').addEventListener('change',()=>{lessonId=$('lesson').value;page=0;renderQuestions();});$('search').addEventListener('input',()=>{query=$('search').value.trim().toLocaleLowerCase();page=0;renderQuestions();});$('previous').addEventListener('click',()=>{page--;renderQuestions();});$('next').addEventListener('click',()=>{page++;renderQuestions();});$('add-lesson').addEventListener('click',()=>{if(lessonId)add(bank().items.filter(i=>i.lessonId===lessonId).map(i=>i.id));});$('clear').addEventListener('click',()=>{if(confirm('Remove all '+draft.itemIds.length+' questions from this draft? Undo is available until your next draft change. Downloaded files and source banks will remain.')){remove([...draft.itemIds]);status('Draft cleared. You can undo or start a new selection.');}});$('clear-bank').addEventListener('click',()=>{const ids=draft.itemIds.filter(id=>itemMap.get(id).bankId===bankId);if(confirm('Remove '+ids.length+' questions from '+bank().display+'? Other banks will remain. You can undo this change.'))remove(ids);});$('undo').addEventListener('click',()=>{if(!undo)return;draft=undo;undo=null;dirty=true;syncDraftFields();renderQuestions();renderDraft();status('Last draft change undone.');});$('draft-title').addEventListener('change',()=>change(()=>{draft.title=$('draft-title').value;}));$('purpose').addEventListener('change',()=>change(()=>{draft.purpose=$('purpose').value;}));$('download').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(draftRecord(),null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='studio-practice-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dirty=false;status('Draft downloaded. Keep this file to reopen your selections.');});$('content-files').addEventListener('change',()=>loadContent([...$('content-files').files]));$('draft-file').addEventListener('change',()=>openDraft($('draft-file').files[0]));$('forget-content').addEventListener('click',()=>{if(confirm('Unload source previews for '+loaded.size+' banks from this page? Your draft and downloaded files will remain. You can reload the same source files.')){loaded.clear();$('forget-content').disabled=true;$('bank-info').textContent=bank().items.length.toLocaleString()+' indexed questions. Source content not loaded.';renderQuestions();renderPreview();status('Source previews unloaded. Your draft is unchanged.');}});window.addEventListener('beforeunload',e=>{if(dirty&&draft.itemIds.length){e.preventDefault();e.returnValue='';}});setBank();status('5,425 English records: '+engineMap.size+' questions support new number variants. Other records remain source previews.');
}catch(e){status('The catalog could not open. Use a current Chrome or Edge browser and reopen the complete downloaded HTML file. '+e.message,true);}
})();
