/* Teacher selection over canonical concept evidence; draft operations stay in the host. */
(function(root){'use strict';let ctx,host,origin=null,offset=0,last=null;const pending=new Set(),R=()=>MathEngineBanks.relatedConcepts,$=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function button(text,fn){const b=el('button',text);b.type='button';b.addEventListener('click',fn);return b;}
function select(id,label,options,parent){const wrap=el('div'),l=el('label',label),s=el('select');s.id=id;l.htmlFor=id;for(const [value,text]of options){const o=el('option',text);o.value=value;s.append(o);}wrap.append(l,s);parent.append(wrap);return s;}
function bankLabel(id){return ctx.banks.find(b=>b.id===id).display.replace(' · English','');}
function mode(value){$('discovery-mode').value=value;$('concept-panel').hidden=value!=='concepts';$('progression-panel').hidden=value!=='progression';}
function mount(context){ctx=context;const parent=$('connections'),old=el('div');old.id='progression-panel';while(parent.firstChild)old.append(parent.firstChild);const nav=el('div',undefined,'discovery-nav');select('discovery-mode','Find tasks by',[['concepts','Related Concepts'],['progression','Difficulty / Progression']],nav).addEventListener('change',e=>mode(e.target.value));parent.append(nav);host=el('section');host.id='concept-panel';parent.append(host,old);host.append(el('p','WHOLE-CURRICULUM CONNECTIONS','eyebrow'),el('h2','Explore related concepts'),el('p','Find useful connections across Grade 3 through Algebra 2. Preview tasks and choose what fits your lesson, study guide or practice packet.'));
const help=el('details');help.className='connections-help';help.append(el('summary','? What do these connections mean?'),el('p','Shared concept means a common reviewed focus, not equal difficulty. Supporting ideas, applications and representations explain a recorded one-step connection. Related strand is broader. Use Difficulty / Progression for the separately reviewed easier, harder and prerequisite relationships.'),el('p','Earlier and later follow the curriculum sequence, not a difficulty ranking. Algebra 1/2 is a tracked course, not a fixed grade. Reused question generators are grouped; expand a card to choose another original lesson. No selections enter your draft until you add them.'),el('p','Course counts show matching working entries and distinct question generators before course filters. “No recorded connection” is a mapping limit; “No working task mapped to this concept” does not prove that the curriculum lacks the topic. Every current working entry has concept tags. This does not cover every publisher question variant.'));host.append(help);
const controls=el('div',undefined,'connections-controls'),wrap=el('div'),label=el('label','Concept search'),search=el('input');search.id='concept-search';search.type='search';search.placeholder='Try GCF, prime factorization, triangles or Pythagoras';label.htmlFor=search.id;wrap.append(label,search);controls.append(wrap);select('concept-topic','Concept or strand',[],controls);select('concept-origin','Starting task',[],controls);select('concept-scope','Course range',[['all','All courses'],['this','This course'],['earlier','Earlier courses'],['later','Later courses']],controls);select('concept-bank','Specific course',[['','Any course'],...ctx.banks.map(b=>[b.id,bankLabel(b.id)])],controls);select('concept-kind','Connection type',[['all','All concept connections'],...Object.entries(R().labels)],controls);const repeat=el('input');repeat.type='checkbox';repeat.id='concept-repeat';const rl=el('label');rl.append(repeat,document.createTextNode(' Include repeated generators'));controls.append(rl);host.append(controls);
const contextNode=el('div');contextNode.id='concept-context';const coverage=el('div');coverage.id='concept-coverage';const status=el('p');status.id='concept-status';status.setAttribute('role','status');const selection=el('div',undefined,'actions');selection.id='concept-selection';const cards=el('div',undefined,'connection-cards');cards.id='concept-results';const pager=el('div',undefined,'actions');pager.id='concept-pagination';host.append(contextNode,coverage,status,selection,cards,pager);
search.addEventListener('input',populateConcepts);$('concept-topic').addEventListener('change',populateOrigins);$('concept-origin').addEventListener('change',()=>{origin=$('concept-origin').value||null;offset=0;render();});for(const id of ['concept-scope','concept-bank','concept-kind','concept-repeat'])$(id).addEventListener('change',()=>{offset=0;render();});populateConcepts();mode('concepts');}
function populateConcepts(){const node=$('concept-topic'),previous=node.value;node.replaceChildren();for(const c of R().search($('concept-search').value)){const o=el('option',c.label+(c.kind==='strand'?' — broad strand':''));o.value=c.id;node.append(o);}if([...node.options].some(o=>o.value===previous))node.value=previous;populateOrigins();}
function populateOrigins(){const select=$('concept-origin'),previous=origin;select.replaceChildren();const concept=$('concept-topic').value;if(concept)for(const p of R().browse(concept)){const o=el('option',p.title+' — '+bankLabel(p.bankId)+' — '+ctx.lessonLabel(ctx.itemMap.get(p.sourceId)));o.value=p.sourceId;select.append(o);}if([...select.options].some(o=>o.value===previous))select.value=previous;origin=select.value||null;offset=0;render();}
function open(id){const p=R().lookup(id);if(!p)throw Error('No concept mapping for this working task.');$('concept-search').value='';origin=id;populateConcepts();$('concept-topic').value=p.conceptIds.find(id=>id.startsWith('focus:'))||p.conceptIds[0];origin=id;populateOrigins();$('concept-scope').value='all';$('concept-bank').value='';$('concept-kind').value='all';offset=0;render();mode('concepts');host.scrollIntoView({behavior:'smooth',block:'start'});$('concept-scope').focus({preventScroll:true});}
function selections(){const n=$('concept-selection');n.replaceChildren(el('span',pending.size+' task(s) selected across pages and filters.'));const add=button('Add selected to draft',()=>{ctx.add([...pending]);const added=new Set(ctx.getDraft().itemIds);for(const id of pending)if(added.has(id))pending.delete(id);render();});add.disabled=!pending.size;const clear=button('Clear selection',()=>{pending.clear();render();});clear.disabled=!pending.size;n.append(add,clear);}
function render(){if(!host)return;selections();const list=$('concept-results'),context=$('concept-context'),coverage=$('concept-coverage'),pager=$('concept-pagination');list.replaceChildren();context.replaceChildren();coverage.replaceChildren();pager.replaceChildren();if(!origin){$('concept-status').textContent=$('concept-topic').value?'No working task mapped to this concept.':'No matching concept. Try another term or spelling.';return;}
const p=MathEngineBanks.connections.lookup(origin),draft=new Set(ctx.getDraft().itemIds);context.append(el('h3',p.title),el('p',bankLabel(p.bankId)+' · '+ctx.lessonLabel(ctx.itemMap.get(origin))),button('Preview starting task',()=>ctx.preview(origin)),button(draft.has(origin)?'Remove starting task':'Add starting task',()=>{draft.has(origin)?ctx.remove([origin]):ctx.add([origin]);render();}));
const tags=R().lookup(origin).conceptIds.map(id=>R().concepts.find(c=>c.id===id).label);context.append(el('p','Mapped concepts: '+tags.join(' · '),'muted'));last=R().find(origin,{scope:$('concept-scope').value,bankId:$('concept-bank').value,kind:$('concept-kind').value,includeRepeated:$('concept-repeat').checked,offset,limit:24});
coverage.append(el('strong','Connection coverage across courses'));const grid=el('div',undefined,'concept-course-counts');for(const c of last.counts){const b=button(bankLabel(c.bankId)+': '+c.entries+' tasks / '+c.providers+' generators',()=>{$('concept-bank').value=c.bankId;$('concept-scope').value='all';offset=0;render();});b.title=c.status==='available'?'Show matching tasks in this course':c.status==='mapping-incomplete'?'Some working tasks have no concept mapping':'No recorded connection for these filters';grid.append(b);}coverage.append(grid,el('small','Counts include all courses before course-range filters. Zero means no recorded match, not proof of no mathematical connection.'));
$('concept-status').textContent=last.totalProviders?last.totalEntries+' matching lesson entries in '+last.totalProviders+' distinct generators. Showing '+(offset+1)+'–'+Math.min(offset+24,last.totalProviders)+'.':last.status==='mapping-missing'?'This working entry needs a concept mapping.':'No recorded connection matches these filters. Try all courses or another connection type.';
for(const r of last.results){const card=el('article',undefined,'connection-card');card.dataset.providerId=r.providerSourceId;const relation=r.relations[0];card.append(el('span',relation.label,'connection-type'),el('h3',r.profile.title),el('p',relation.reason),el('p',relation.limit,'muted'));if(r.relations.length>1){const more=el('details');more.append(el('summary','Other recorded connections ('+(r.relations.length-1)+')'));for(const rr of r.relations.slice(1))more.append(el('p',rr.label+': '+rr.reason+' '+rr.limit));card.append(more);}
const picker=el('select');picker.setAttribute('aria-label','Original course and lesson');for(const p of r.occurrences){const option=el('option',bankLabel(p.bankId)+' · '+ctx.lessonLabel(ctx.itemMap.get(p.sourceId))+' · '+p.sourceId);option.value=p.sourceId;picker.append(option);}card.append(el('p',r.occurrences.length+' matching lesson occurrence(s); same generator.'),picker);const actions=el('div',undefined,'actions'),check=el('input');check.type='checkbox';check.setAttribute('aria-label','Select task for batch add');check.checked=pending.has(picker.value);check.addEventListener('change',()=>{check.checked?pending.add(picker.value):pending.delete(picker.value);selections();});const selectLabel=el('label');selectLabel.append(check,document.createTextNode(' Select'));const add=button('',()=>{const id=picker.value;ctx.getDraft().itemIds.includes(id)?ctx.remove([id]):ctx.add([id]);render();});function update(){check.checked=pending.has(picker.value);add.textContent=ctx.getDraft().itemIds.includes(picker.value)?'Remove':'Add to draft';}picker.addEventListener('change',update);update();actions.append(selectLabel,button('Preview',()=>ctx.preview(picker.value)),button('Use as starting task',()=>open(picker.value)),add);card.append(actions);list.append(card);}
const previous=button('Previous concepts page',()=>{offset=Math.max(0,offset-24);render();list.scrollTop=0;}),next=button('Next concepts page',()=>{offset+=24;render();list.scrollTop=0;});previous.disabled=offset===0;next.disabled=!last.hasMore;pager.append(previous,next);}
root.StudioConcepts={mount,open,refresh:render,mode};
})(globalThis);
