/* Teacher discovery over the canonical Engine connection map. */
(function(root){'use strict';let host,ctx,origin=null;const C=()=>MathEngineBanks.connections,$=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function button(text,fn){const b=el('button',text);b.type='button';b.addEventListener('click',fn);return b;}
function field(id,text,node){const l=el('label',text);node.id=id;l.htmlFor=id;const w=el('div');w.append(l,node);return w;}
function select(options){const s=el('select');for(const [value,label]of options){const o=el('option',label);o.value=value;s.append(o);}return s;}
function course(p){return p.course+(p.localGrade?' · Grade '+p.localGrade:' · school grade unassigned');}
function mount(context){ctx=context;host=$('connections');host.append(el('p','CROSS-COURSE PRACTICE','eyebrow'),el('h2','Find easier, harder and related tasks'));const intro=el('p','Choose a topic and starting task, or use “Find related tasks” in a question preview. Preview a suggestion and add it to your draft; existing selections stay in place.');host.append(intro);const help=el('details',undefined,'connections-help');help.append(el('summary','? How connections and difficulty work'),el('p','Easier and harder compare reviewed mathematical demands, not grade labels or student scores. A prerequisite supports another construct; an extension introduces a new demand. Related tasks have no validated difficulty comparison. Individual number variants can differ in difficulty. Repeated providers are excluded unless you request them.'),el('p','Only Introduction to PreAlgebra (8/7) has the confirmed local Grade 5 label. Other courses retain their textbook names. Topic coverage includes every working task; directed comparisons are limited to the reviewed paths. This does not change GradeCam targeting.'));host.append(help);
 const controls=el('div',undefined,'connections-controls'),search=el('input');search.type='search';search.placeholder='Search topics';const topic=select([]),from=select([]),relation=select([['all','All reviewed connections'],...Object.entries(C().relationLabels)]),target=select([['','Any other course'],...ctx.banks.map(b=>[b.id,b.display.replace(' · English','')])]);controls.append(field('connection-search','Topic search',search),field('connection-topic','Topic',topic),field('connection-origin','Starting task',from),field('connection-relation','Connection type',relation),field('connection-bank','Suggested course',target));const same=el('input');same.type='checkbox';same.id='connection-same-bank';const sameLabel=el('label');sameLabel.append(same,document.createTextNode(' Include suggestions from the starting course'));controls.append(sameLabel);host.append(controls,el('p','','muted'));const selected=host.lastChild;selected.id='connection-context';const status=el('p');status.id='connection-status';status.setAttribute('role','status');host.append(status);const cards=el('div',undefined,'connection-cards');cards.id='connection-results';host.append(cards);
 function topics(){const old=topic.value,terms=search.value.toLowerCase().trim();topic.replaceChildren();for(const t of C().topics.filter(t=>t.label.toLowerCase().includes(terms))){const o=el('option',t.label+' · '+t.entryCount);o.value=t.id;topic.append(o);}if([...topic.options].some(o=>o.value===old))topic.value=old;populate();}
 search.addEventListener('input',topics);topic.addEventListener('change',populate);from.addEventListener('change',()=>{origin=from.value||null;render();});for(const n of [relation,target,same])n.addEventListener('change',render);topics();}
function populate(){const s=$('connection-origin'),previous=origin;s.replaceChildren();const topic=$('connection-topic').value;if(topic)for(const p of C().browse(topic)){const op=el('option',p.title+' — '+p.course+' — '+(ctx.itemMap.get(p.sourceId)?.sourceId||p.sourceId));op.value=p.sourceId;s.append(op);}if([...s.options].some(o=>o.value===previous))s.value=previous;origin=s.value||null;render();}
function open(id){const p=C().lookup(id);$('connection-search').value='';const s=$('connection-topic');s.replaceChildren();for(const t of C().topics){const op=el('option',t.label+' · '+t.entryCount);op.value=t.id;s.append(op);}s.value=p.topic;origin=id;$('connection-relation').value='all';$('connection-bank').value='';populate();host.scrollIntoView({behavior:'smooth',block:'start'});$('connection-relation').focus({preventScroll:true});}
function render(){if(!host)return;const list=$('connection-results');list.replaceChildren();if(!origin){$('connection-context').textContent='';$('connection-status').textContent='No matching topic. Try another search.';return;}const p=C().lookup(origin),selected=new Set(ctx.getDraft().itemIds),mode=$('connection-relation').value;const context=$('connection-context');context.replaceChildren(el('strong',p.title),el('span',' — '+course(p)+' · '+ctx.lessonLabel(ctx.itemMap.get(origin))+' '),button('Preview starting task',()=>ctx.preview(origin)),button(selected.has(origin)?'Remove starting task':'Add starting task',()=>{selected.has(origin)?ctx.remove([origin]):ctx.add([origin]);render();}));if(!p.memberships.length)context.append(el('p','This task has topic links, but no reviewed easier/harder comparison. Explore related tasks or choose a reviewed starting task.'));
 const results=C().suggestions(origin,{relation:mode,crossBankOnly:!$('connection-same-bank').checked,targetBank:$('connection-bank').value,limit:100});$('connection-status').textContent=results.length?results.length+' suggestion(s). No selections change until you choose Add.':'No reviewed '+(mode==='all'?'':C().relationLabels[mode].toLowerCase()+' ')+'connection matches these filters. Try another connection type or include the starting course.';
 for(const r of results){const card=el('article',undefined,'connection-card');card.dataset.sourceId=r.sourceId;card.dataset.relation=r.type;card.append(el('span',r.label,'connection-type'),el('h3',r.profile.title),el('p',course(r.profile),'muted'),el('p',ctx.lessonLabel(ctx.itemMap.get(r.sourceId)),'muted'),el('p',r.reason));if(r.prerequisites)card.append(el('p','Needed background: '+r.prerequisites));card.append(el('small',r.profile.answerKinds.includes('teacher')?'Includes teacher-reviewed work.':'Check the preview for the exact response format.'));const actions=el('div',undefined,'actions');actions.append(button('Preview',()=>ctx.preview(r.sourceId)),button('Use as starting task',()=>open(r.sourceId)),button(selected.has(r.sourceId)?'Remove':'Add to draft',()=>{selected.has(r.sourceId)?ctx.remove([r.sourceId]):ctx.add([r.sourceId]);render();}));card.append(actions);list.append(card);}}
root.StudioConnections={mount,open,refresh:render};
})(globalThis);
