(function(root){'use strict';
const VERSION='0.21.0-rc.2', CATALOG='course-index-0.1+recovery-0.2',MAX=1000;
function textPreview(s){return String(s??'').replace(/\x0f|\[\]/g,'[equation or diagram not rendered]').replace(/\x10/g,'\n').replace(/\x11/g,' | ').replace(/[\x00-\x08\x0b\x0c\x0e\x12-\x1f]/g,'[formatting]');}
function validateDraft(d,itemMap){if(!d||d.format!=='studio-manual-draft'||![1,2].includes(d.version)||d.catalog!==CATALOG)throw Error('This is not a draft for the current Studio catalog.');if(typeof d.title!=='string'||d.title.length>120||!['test','practice'].includes(d.purpose)||!Array.isArray(d.itemIds)||d.itemIds.length>MAX)throw Error('Draft title, purpose, or question count is invalid.');const seen=new Set();for(const id of d.itemIds){if(typeof id!=='string'||!itemMap.has(id)||seen.has(id))throw Error('Draft contains an unknown, Spanish, or repeated question. Spanish banks have been removed.');seen.add(id);}const generation=d.generation||{seed:'practice',indices:{}};if(typeof generation.seed!=='string'||!generation.seed.trim()||generation.seed.length>200||!generation.indices||typeof generation.indices!=='object'||Array.isArray(generation.indices)||Object.entries(generation.indices).some(([id,n])=>!itemMap.has(id)||!Number.isSafeInteger(n)||n<0))throw Error('Invalid generator seed or variant index.');return {title:d.title,purpose:d.purpose,itemIds:[...d.itemIds],generation:JSON.parse(JSON.stringify(generation))};}
function normalizeContent(d,bank){const sourceItems=bank.items.filter(i=>i.origin!=='original-curriculum-task');if(!d||d.id!==bank.id||!Array.isArray(d.items)||d.items.length!==sourceItems.length)throw Error('Recovered content does not match this course bank.');const valid=new Set(sourceItems.map(i=>i.id)),seen=new Set(),records=new Map();for(const i of d.items){if(!valid.has(i.id)||seen.has(i.id))throw Error('Recovered content has unknown or repeated questions.');seen.add(i.id);let prompt,answer,choices=[],dynamic=false;
if(Array.isArray(i.blocks)){prompt=i.question_block_indices.map(j=>i.blocks[j].text).join('\n');answer=i.answer_block_indices.map(j=>i.blocks[j].text).join('\n');choices=i.other_answer_block_indices.map((j,n)=>({label:String(n+1),text:i.blocks[j].text}));dynamic=i.script_block_indices.some(j=>i.blocks[j].text);}
else {prompt=i.stem_text_with_controls;answer=i.answer?.text_with_controls;choices=(i.choices_in_source_layout_order||[]).map(c=>({label:c.label,text:c.text_with_controls})).sort((a,b)=>a.label.localeCompare(b.label));dynamic=i.dynamic_data_length>4;}
records.set(i.id,{prompt:textPreview(prompt),answer:textPreview(answer),choices:choices.map(c=>({label:c.label,text:textPreview(c.text)})),choiceKey:i.answer?.kind==='choice'?i.answer.label:null,dynamic,choiceConventionUnverified:Array.isArray(i.blocks)&&!i.answer_block_indices.length,searchText:String(prompt??'').toLocaleLowerCase()});}return records;}
const api={VERSION,CATALOG,MAX,textPreview,validateDraft,normalizeContent};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.StudioCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
