/* Local XLSX input and Word output; no remote calls. */
(function(root){'use strict';
const xml=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('Malformed workbook XML.');return d;},nodes=(n,t)=>Array.from(n.getElementsByTagNameNS('*',t)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
async function xlsx(buffer){if(buffer.byteLength>15000000)throw Error('Workbook is too large (15 MB limit).');const zip=await JSZip.loadAsync(buffer);let expanded=0;for(const f of Object.values(zip.files)){expanded+=f._data?.uncompressedSize||0;if(expanded>60000000)throw Error('Workbook expanded size exceeds 60 MB.');}async function part(p){const f=zip.file(p);if(!f)throw Error('Workbook is missing '+p);return xml(await f.async('string'));}
 const workbook=await part('xl/workbook.xml'),rels=await part('xl/_rels/workbook.xml.rels'),sheets=nodes(workbook,'sheet'),selected=sheets.filter(s=>s.getAttribute('name').trim()==='Student By Standard');if(selected.length!==1)throw Error('Select a workbook containing one sheet named Student By Standard.');const id=selected[0].getAttribute('r:id'),rel=nodes(rels,'Relationship').find(r=>r.getAttribute('Id')===id);if(!rel||rel.getAttribute('TargetMode')==='External')throw Error('External workbook sheets are not supported.');const target=rel.getAttribute('Target');let path=target.startsWith('/')?target.slice(1):'xl/'+target;if(path.includes('..')||!path.startsWith('xl/'))throw Error('Invalid sheet path.');
 const shared=zip.file('xl/sharedStrings.xml')?nodes(await part('xl/sharedStrings.xml'),'si').map(s=>nodes(s,'t').map(t=>t.textContent).join('')):[];const sheet=await part(path),rows=[];
 for(const row of nodes(sheet,'row')){const n=Number(row.getAttribute('r'));if(!Number.isInteger(n)||n<1||n>10000)throw Error('Workbook row limit exceeded.');const cells=[];for(const cell of nodes(row,'c')){const ref=cell.getAttribute('r')||'',match=/^([A-Z]+)\d+$/.exec(ref);if(!match)throw Error('Invalid cell address.');let col=0;for(const c of match[1])col=col*26+c.charCodeAt(0)-64;if(col>1200)throw Error('Workbook column limit exceeded.');const t=cell.getAttribute('t'),raw=nodes(cell,'v')[0]?.textContent;let v;if(t==='s'){v=shared[Number(raw)];if(v===undefined)throw Error('Invalid shared string.');}else if(t==='inlineStr')v=nodes(cell,'t').map(t=>t.textContent).join('');else if(t==='b')v=raw==='1';else if(t==='e')v='#ERROR';else if(raw!==undefined)v=t==='str'?raw:Number(raw);else v=null;cells[col-1]={v,f:nodes(cell,'f').length>0};}rows[n-1]=cells;}return Array.from({length:rows.length},(_,n)=>rows[n]||[]);
}
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',M='http://schemas.openxmlformats.org/officeDocument/2006/math';
function run(t,bold=false){return '<w:r><w:rPr>'+(bold?'<w:b/>':'')+'</w:rPr><w:t xml:space="preserve">'+esc(t)+'</w:t></w:r>';}
function math(n){if(n.nodeType===3)return n.textContent.trim()?'<m:r><m:t>'+esc(n.textContent)+'</m:t></m:r>':'';const c=Array.from(n.childNodes),tag=n.localName;if(tag==='mfrac')return '<m:f><m:num>'+math(c[0])+'</m:num><m:den>'+math(c[1])+'</m:den></m:f>';if(tag==='msup')return '<m:sSup><m:e>'+math(c[0])+'</m:e><m:sup>'+math(c[1])+'</m:sup></m:sSup>';if(tag==='msub')return '<m:sSub><m:e>'+math(c[0])+'</m:e><m:sub>'+math(c[1])+'</m:sub></m:sSub>';if(tag==='msqrt')return '<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e>'+c.map(math).join('')+'</m:e></m:rad>';if(['mn','mi','mo','mtext'].includes(tag))return '<m:r><m:t xml:space="preserve">'+esc(n.textContent)+'</m:t></m:r>';return c.map(math).join('');}
function para(r,style=''){return '<w:p><w:pPr>'+style+'</w:pPr>'+r+'</w:p>';}
async function docx(batch,mode){if(!['student','key','study'].includes(mode))throw Error('Choose an output type.');const F=StudioPacketFormat,base=StudioPacketCore.settings(batch.settings),zip=new JSZip(),rels=[],images=[],parts=[];let imageId=0,s=base,columnWidth=0;const mm=n=>Math.round(n*1440/25.4),width=base.paper==='A4'?11906:12240,height=base.paper==='A4'?16838:15840;
 async function image(svg,contentWidth=columnWidth){const vb=(svg.getAttribute('viewBox')||'0 0 400 240').split(/[ ,]+/).map(Number);const maxW=contentWidth/1440*96,maxH=mode==='student'?300:210,w=Math.min(maxW,480,maxH*vb[2]/vb[3]),h=w*vb[3]/vb[2];if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0)throw Error('Invalid diagram dimensions.');const copy=svg.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width',w*3);copy.setAttribute('height',h*3);copy.style.color='#111';const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'}));let png;try{const img=new Image();await new Promise((yes,no)=>{img.onload=yes;img.onerror=()=>no(Error('Diagram export failed. Your packet is preserved.'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=Math.ceil(w*3);canvas.height=Math.ceil(h*3);const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);png=canvas.toDataURL('image/png').split(',')[1];}finally{URL.revokeObjectURL(url);}const id=++imageId,cx=Math.round(w*9525),cy=Math.round(h*9525);zip.file('word/media/image'+id+'.png',png,{base64:true});rels.push('<Relationship Id="img'+id+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image'+id+'.png"/>');images.push(id);return '<w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'+cx+'" cy="'+cy+'"/><wp:docPr id="'+id+'" name="Question diagram" descr="'+esc(svg.getAttribute('aria-label')||'Mathematical diagram')+'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="diagram.png"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="img'+id+'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+cx+'" cy="'+cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>';}
 function inline(n,bold=false){if(n.nodeType===3)return run(n.textContent,bold);if(n.localName==='math')return '<m:oMath>'+math(n)+'</m:oMath>';if(n.localName==='br')return '<w:r><w:br/></w:r>';return Array.from(n.childNodes).map(c=>inline(c,bold||n.localName==='strong')).join('');}
 async function html(n,contentWidth=columnWidth){
 // Keep each option label with its diagram and preserve the visual choice grid in Word.
 const choices=n.nodeType===1?Array.from(n.children):[];
 if(choices.length>=2&&choices.every(c=>/^Option [A-Z]$/.test(c.querySelector(':scope > strong')?.textContent||'')&&c.querySelector('svg'))){
  const columns=s.distractors==='vertical'?1:s.distractors==='horizontal'?2:s.columns===1?2:1,cellWidth=Math.floor(contentWidth/columns),parts=[];
  for(let start=0;start<choices.length;start+=columns){let row='<w:tr><w:trPr><w:cantSplit/></w:trPr>';
   for(let j=0;j<columns;j++){const choice=choices[start+j];row+='<w:tc><w:tcPr><w:tcW w:w="'+cellWidth+'" w:type="dxa"/></w:tcPr>'+(choice?await html(choice,cellWidth-180):para(''))+para('','<w:spacing w:after="0" w:line="20" w:lineRule="exact"/>')+'</w:tc>';}
   parts.push(row+'</w:tr>');
  }
  return '<w:tbl><w:tblPr><w:tblW w:w="'+contentWidth+'" w:type="dxa"/><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid>'+Array.from({length:columns},()=>'<w:gridCol w:w="'+cellWidth+'"/>').join('')+'</w:tblGrid>'+parts.join('')+'</w:tbl>'+para('','<w:spacing w:after="0" w:line="20" w:lineRule="exact"/>');
 }
if(n.localName==='ol'){const list=[...n.children];if(s.distractors==='horizontal'){let rows='';for(let i=0;i<list.length;i+=2){rows+='<w:tr><w:trPr><w:cantSplit/></w:trPr>';for(let j=0;j<2;j++)rows+='<w:tc><w:tcPr><w:tcW w:w="'+Math.floor(contentWidth/2)+'" w:type="dxa"/></w:tcPr>'+para(list[i+j]?run(String.fromCharCode(65+i+j)+'. ')+inline(list[i+j]):'')+'</w:tc>';rows+='</w:tr>';}return '<w:tbl><w:tblPr><w:tblW w:w="'+contentWidth+'" w:type="dxa"/><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid><w:gridCol w:w="'+Math.floor(contentWidth/2)+'"/><w:gridCol w:w="'+Math.floor(contentWidth/2)+'"/></w:tblGrid>'+rows+'</w:tbl>'+para('');}return list.map((li,i)=>para(run(String.fromCharCode(65+i)+'. ')+inline(li),'<w:keepNext/>')).join('');}if(n.nodeType===3)return n.textContent.trim()?para(run(n.textContent),'<w:keepNext/>'):'';if(n.localName==='svg')return para(await image(n,contentWidth),'<w:keepNext/>');if(n.localName==='math')return para('<m:oMath>'+math(n)+'</m:oMath>','<w:keepNext/>');if(n.localName==='table'){const rows=Array.from(n.querySelectorAll('tr'));const count=Math.max(...rows.map(r=>r.children.length));let t='<w:tbl><w:tblPr><w:tblW w:w="'+columnWidth+'" w:type="dxa"/><w:tblBorders>'+['top','left','bottom','right','insideH','insideV'].map(x=>'<w:'+x+' w:val="single" w:sz="4" w:color="999999"/>').join('')+'</w:tblBorders><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid>'+Array.from({length:count},()=>'<w:gridCol w:w="'+Math.floor(columnWidth/count)+'"/>').join('')+'</w:tblGrid>';for(const row of rows){t+='<w:tr><w:trPr><w:cantSplit/></w:trPr>';for(const cell of row.children)t+='<w:tc><w:tcPr><w:tcW w:w="'+Math.floor(columnWidth/count)+'" w:type="dxa"/></w:tcPr>'+para(inline(cell,cell.localName==='th'),'<w:keepNext/>')+'</w:tc>';t+='</w:tr>';}return t+'</w:tbl>';}
 if(['p','li','h3','h4','figcaption'].includes(n.localName))return para(inline(n),'<w:keepNext/>');const parts=[];for(const c of n.childNodes)parts.push(await html(c,contentWidth));return parts.join('');}
 const ns='xmlns:w="'+W+'" xmlns:m="'+M+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"';
 const border=rule=>rule==='none'?'':'<w:pBdr>'+((rule==='above'||rule==='both')?'<w:top w:val="single" w:sz="4" w:space="4" w:color="999999"/>':'')+((rule==='below'||rule==='both')?'<w:bottom w:val="single" w:sz="4" w:space="4" w:color="999999"/>':'')+'</w:pBdr>';
 function tokenRuns(text,p){return text.split(/(\{page\})/).map(t=>t==='{page}'?'<w:fldSimple w:instr="PAGE"/>':run(F.tokens(t,p,s,''))).join('');}
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
 function lineHeight(text,points=base.fontSize){ctx.font=points+'pt "'+base.fontFamily+'"';const pixels=(width-mm(base.marginLeft+base.marginRight))/1440*96;let lines=0;for(const line of String(text).split('\n'))lines+=Math.max(1,Math.ceil(ctx.measureText(line).width/pixels));return lines*points*base.lineSpacing*20+mm(1);}
 function bandText(part,type){if(s[part+'Target']!=='all'&&s[part+'Target']!==mode)return'';return s[part+(type==='first'?'First':type==='even'?'Even':'Odd')]||s[part]||'';}
 function header(p,section,type,answerSheet){const label=answerSheet?'Answer sheet':mode==='student'?(s.purpose==='test'?'Test':'Practice'):mode==='key'?'Teacher key':'Study guide',lines=[s.title,...(s.studentNameHeader&&p.name?[p.name]:[]),label+(section.title?' · '+section.title:'')],custom=bandText('header',type);if(custom)lines.push(F.tokens(custom,p,s,'888'));if(mode==='student'&&type==='first')lines.push((p.name?'':'Name ____________________   ')+'Date ____________________');if(s.instructionsPlacement==='every'||s.instructionsPlacement==='first'&&type==='first')lines.push(s.instructions);let h=para(run(lines[0],true),'<w:pStyle w:val="Title"/>');for(let i=1;i<lines.length;i++)h+=para(i===(s.studentNameHeader&&p.name?3:2)&&custom?tokenRuns(custom,p):run(lines[i],s.studentNameHeader&&p.name&&i===1),'<w:spacing w:after="'+mm(1)+'"/>'+(i===lines.length-1?border(s.headerRule):''));return{xml:h,height:lines.reduce((n,t,i)=>n+lineHeight(t,i?base.fontSize:17),0)+mm(3)};}
 function footer(p,type){const custom=bandText('footer',type);return{xml:para(tokenRuns(custom,p)+run('   Page ')+ '<w:fldSimple w:instr="PAGE"/>',border(s.footerRule)),height:lineHeight(F.tokens(custom,p,s,'888')+'   Page 888')+mm(4)};}
 let body='',sectionNo=0;
 function sectionProperties(p,section,answerSheet){const id=++sectionNo;let refs='',headHeight=0,footHeight=0;for(const type of ['default','first','even'])for(const part of ['header','footer']){const data=part==='header'?header(p,section,type,answerSheet):footer(p,type),name=part+id+'-'+type;parts.push({name,part});zip.file('word/'+name+'.xml','<w:'+(part==='header'?'hdr':'ftr')+' '+ns+'>'+data.xml+'</w:'+(part==='header'?'hdr':'ftr')+'>');rels.push('<Relationship Id="'+name+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/'+part+'" Target="'+name+'.xml"/>');refs+='<w:'+part+'Reference w:type="'+type+'" r:id="'+name+'"/>';if(part==='header')headHeight=Math.max(headHeight,data.height);else footHeight=Math.max(footHeight,data.height);}
 const top=mm(s.marginTop)+headHeight,bottom=mm(s.marginBottom)+footHeight;if(height-top-bottom<mm(40))throw Error('Headers and margins leave too little Word question space.');return '<w:sectPr>'+refs+'<w:type w:val="nextPage"/><w:pgSz w:w="'+width+'" w:h="'+height+'"/><w:pgMar w:top="'+top+'" w:right="'+mm(s.marginRight)+'" w:bottom="'+bottom+'" w:left="'+mm(s.marginLeft)+'" w:header="'+mm(s.marginTop)+'" w:footer="'+mm(s.marginBottom)+'"/><w:cols w:num="'+(answerSheet?1:s.columns)+'" w:space="'+mm(s.columnGap)+'" w:sep="'+(s.verticalDivider?'1':'0')+'"/><w:titlePg/></w:sectPr>';}
 const sections=[];for(const p of batch.packets){for(const section of F.sections(p,base))sections.push({p,section,answerSheet:false});if(mode==='student'&&base.answerBlank==='separate')sections.push({p,section:{title:'',settings:{...base,columns:1},items:p.items},answerSheet:true});}
 for(let si=0;si<sections.length;si++){const{p,section,answerSheet}=sections[si];s=section.settings;columnWidth=Math.floor((width-mm(s.marginLeft+s.marginRight+(s.columns-1)*s.columnGap))/s.columns);const sect=sectionProperties(p,section,answerSheet);
 for(let qi=0;qi<section.items.length;qi++){const item=section.items[qi],f=F.item(item.layout);if(qi&&['page','column'].includes(f.breakBefore))body+=para('<w:r><w:br w:type="'+f.breakBefore+'"/></w:r>','<w:spacing w:after="0" w:line="20" w:lineRule="exact"/>');if(f.keepWithNext){const next=section.items[qi+1];if(!next)throw Error('Keep with next cannot cross the end of a section.');if(F.item(next.layout).breakBefore!=='none')throw Error('Keep with next conflicts with the next question break.');}
 if(answerSheet){body+=para(run(item.number+'.   ')+ '<w:r><w:rPr><w:u w:val="single"/></w:rPr><w:t xml:space="preserve">'+ ' '.repeat(Math.round(s.answerBlankWidth*1.5))+'</w:t></w:r>','<w:spacing w:after="'+mm(5)+'"/><w:keepLines/>');continue;}
 let question='';if(f.annotation)question+=para(run(f.annotation,true),'<w:keepNext/>');if(s.instructionsPlacement==='questions')question+=para(run(s.instructions),'<w:keepNext/>');const blank='<w:r><w:rPr><w:u w:val="single"/></w:rPr><w:t xml:space="preserve">'+' '.repeat(Math.round(s.answerBlankWidth*1.5))+'</w:t></w:r>';
 question+=para(run(String(item.number)+'.',true)+(mode==='student'&&s.answerBlank==='beside'?run('    Answer: ')+blank:''),'<w:keepNext/>');const div=document.createElement('div');div.innerHTML=MathEngineBanks.renderQuestion(item.q);question+=await html(div);
 if(mode!=='student'){question+=para(run('Answer: '+MathEngineBanks.answerText(item.q),true),'<w:keepNext/>');question+=para(run(item.q.solution||''),'<w:keepNext/>');if(item.q.teacherSvg){const d=document.createElement('div');d.innerHTML=item.q.teacherSvg;question+=await html(d);}question+=para(run((item.standard?'Outcome: '+item.standard:'Task: '+MathEngineBanks.catalog.find(c=>c.sourceId===item.sourceId).title)+' · variant '+item.index));}else{if(s.answerBlank==='below')question+=para(run('Answer: ')+blank,'<w:keepNext/>');question+=para(run(' '),'<w:spacing w:after="0" w:line="'+Math.max(20,mm(f.space??s.space))+'" w:lineRule="exact"/>');}
 if(!s.keepTogether)question=question.replaceAll('<w:keepNext/>','');if(s.dividers)question+=para('',border('below'));
 // Tables give Word an editable, indivisible question when requested. Keep-with-next chains use paragraph keep properties.
 if(s.keepTogether&&!f.keepWithNext&&!(qi&&F.item(section.items[qi-1].layout).keepWithNext))body+='<w:tbl><w:tblPr><w:tblW w:w="'+columnWidth+'" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="0" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="'+columnWidth+'"/></w:tblGrid><w:tr><w:trPr><w:cantSplit/></w:trPr><w:tc><w:tcPr><w:tcW w:w="'+columnWidth+'" w:type="dxa"/></w:tcPr>'+question+'</w:tc></w:tr></w:tbl>';else body+=question.replaceAll('<w:pPr>','<w:pPr><w:keepLines/>');body+=para('',(f.keepWithNext?'<w:keepNext/>':'')+'<w:spacing w:after="'+mm(s.questionSpacing)+'" w:line="20" w:lineRule="exact"/>');}
 body+=si===sections.length-1?sect:para('',sect);}
 zip.file('word/document.xml','<?xml version="1.0" encoding="UTF-8"?><w:document '+ns+'><w:body>'+body+'</w:body></w:document>');
 zip.file('word/settings.xml','<w:settings xmlns:w="'+W+'"><w:evenAndOddHeaders/>'+(base.mirrorMargins?'<w:mirrorMargins/>':'')+'<w:compat><w:doNotBalanceTextColumns/></w:compat></w:settings>');
 zip.file('word/styles.xml','<w:styles xmlns:w="'+W+'"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="'+esc(base.fontFamily)+'" w:hAnsi="'+esc(base.fontFamily)+'"/><w:sz w:val="'+Math.round(base.fontSize*2)+'"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="'+mm(base.paragraphSpacing)+'" w:line="'+Math.round(base.lineSpacing*240)+'" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="34"/></w:rPr></w:style></w:styles>');
 zip.file('word/_rels/document.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+rels.join('')+'<Relationship Id="settings" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
 zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="document" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
 zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>'+parts.map(({name,part})=>'<Override PartName="/word/'+name+'.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.'+part+'+xml"/>').join('')+'</Types>');
 return zip.generateAsync({type:'blob',compression:'DEFLATE',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
}
root.StudioPacketIO={xlsx,docx};
})(globalThis);
