/* Teacher-controlled composition. Mathematics remains in the pinned Engine. */
(function(root){'use strict';
const E=typeof module!=='undefined'&&module.exports?require('../vendor/course-banks'):root.MathEngineBanks;
const known=new Map(E.catalog.map(x=>[x.sourceId,x])),clone=x=>JSON.parse(JSON.stringify(x));
const defaults={title:'Introduction to PreAlgebra practice',header:'',instructions:'Show your work. Write each answer clearly.',footer:'',paper:'A4',columns:1,space:30,dividers:false,count:2,cap:40,seed:'practice',purpose:'practice'};
function str(v,max,label){if(typeof v!=='string'||v.length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v))throw Error('Invalid '+label+'.');return v;}
function settings(value={}){const s={...defaults,...value};for(const [k,max]of Object.entries({title:120,header:160,instructions:500,footer:160,seed:200}))str(s[k],max,k);if(!s.title.trim()||!s.seed.trim())throw Error('Title and seed are required.');for(const [k,min,max]of [['columns',1,2],['space',0,80],['count',1,10],['cap',1,100]])if(!Number.isInteger(s[k])||s[k]<min||s[k]>max)throw Error('Invalid '+k+'.');if(!['A4','Letter'].includes(s.paper)||!['test','practice'].includes(s.purpose)||typeof s.dividers!=='boolean')throw Error('Invalid packet options.');return s;}
function cellValue(c){if(c&&typeof c==='object'&&'v'in c)return c.v;return c;}
function score(c,scale){if(c&&typeof c==='object'&&c.f)throw Error('Formula score cells are not supported.');const v=cellValue(c);if(v===null||v===undefined||v==='')return{state:'blank',value:null};if(v==='-')return{state:'hyphen',value:null};if(typeof v==='boolean')throw Error('Boolean is not a score.');let n;if(typeof v==='string'&&/^\s*\d+(?:\.\d+)?\s*%\s*$/.test(v))n=Number(v.replace('%',''));else if((typeof v==='number')||(typeof v==='string'&&/^\s*\d+(?:\.\d+)?\s*$/.test(v))){n=Number(v)*(scale==='proportion'?100:1);}else throw Error('Invalid score.');if(!Number.isFinite(n)||n<0||n>100)throw Error('Score is outside the chosen scale.');return{state:'score',value:n};}
function importRows(rows,scale='proportion'){
 if(!['proportion','percent'].includes(scale)||!Array.isArray(rows)||rows.length>10000)throw Error('Invalid import size or score scale.');
 const candidates=rows.map((r,n)=>({r,n})).filter(({r})=>r.some(c=>String(cellValue(c)).trim()==='Name')&&r.some(c=>String(cellValue(c)).trim()==='GradeCam ID'));
 if(candidates.length!==1)throw Error('Expected one Student By Standard header containing Name and GradeCam ID.');
 const {r:header,n:head}=candidates[0],names=header.map(c=>String(cellValue(c)??'').trim()),nameCol=names.indexOf('Name'),idCol=names.indexOf('ID'),gcCol=names.indexOf('GradeCam ID');
 const columns=[],seen=new Set();for(let col=0;col<names.length;col++){const raw=names[col];if(!/^PS\.MAT\./i.test(raw))continue;let task=null;try{task=E.assessment.lookup(raw);}catch(_){}if(seen.has(task?.standard||raw))throw Error('Duplicate outcome column: '+raw);seen.add(task?.standard||raw);columns.push({col,raw,standard:task?.standard||null,sourceId:task?.sourceId||null});}
 if(!columns.length)throw Error('No PS.MAT standard columns were found.');if(columns.length>1000)throw Error('Too many standard columns.');
 const students=[],ids=new Set();for(let n=head+1;n<rows.length;n++){const row=rows[n];if(!row.some(c=>cellValue(c)!==undefined&&cellValue(c)!==null&&cellValue(c)!==''))continue;const name=String(cellValue(row[nameCol])??'').trim();if(!name){if(columns.some(c=>cellValue(row[c.col])!=null&&cellValue(row[c.col])!==''))throw Error('Missing student name at row '+(n+1));continue;}for(const c of [nameCol,idCol,gcCol].filter(c=>c>=0))if(row[c]?.f)throw Error('Formula identity cell at row '+(n+1));
 const id=String(cellValue(row[idCol])??''),gradeCamId=String(cellValue(row[gcCol])??'');const key=gradeCamId?'gc:'+gradeCamId:id?'id:'+id:'row:'+n;
 if(ids.has(key))throw Error('Repeated student identifier at row '+(n+1));ids.add(key);str(name,160,'student name');str(id,120,'student ID');str(gradeCamId,120,'GradeCam ID');
 const scores={};for(const c of columns){try{scores[c.raw]=score(row[c.col],scale);}catch(e){throw Error('Row '+(n+1)+', '+c.raw+': '+e.message);}}
 students.push({key,name,id,gradeCamId,scores});if(students.length>300)throw Error('Import up to 300 students at a time.');}
 if(!students.length)throw Error('No student rows found.');return{format:'studio-gradecam-review',scale,columns,students,headerRow:head+1};
}
function csv(text){if(typeof text!=='string'||text.length>5000000)throw Error('CSV is too large.');const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else if(!value||quoted)quoted=!quoted;else throw Error('Malformed CSV quote.');}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('Unclosed CSV quote.');if(value||row.length){row.push(value);rows.push(row);}return rows;}
function allocate(data,opt){const threshold=Number(opt.threshold);if(!Number.isFinite(threshold)||threshold<0||threshold>100)throw Error('Threshold must be between 0 and 100.');const s=settings(opt.settings),selected=new Set(opt.students),included=new Set(opt.standards),plans=[];
 for(const learner of data.students.filter(s=>selected.has(s.key))){const items=[];for(const col of data.columns){if(!col.sourceId||!included.has(col.raw))continue;const v=learner.scores[col.raw];if(v.state==='score'?v.value<threshold:opt.includeMissing){for(let n=0;n<s.count;n++)items.push({sourceId:col.sourceId,index:n,standard:col.standard,importedCode:col.raw,evidence:clone(v)});}}
 plans.push({name:learner.name,key:learner.key,items:items.slice(0,s.cap),omitted:Math.max(0,items.length-s.cap)});}
 return plans;
}
function freeze(x){if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;}
function generate(plans,value){const s=settings(value);if(!Array.isArray(plans)||!plans.length||plans.length>300)throw Error('Choose at least one packet, up to 300.');let total=0;const packets=[];for(const plan of plans){str(plan.name,160,'packet name');if(!Array.isArray(plan.items)||!plan.items.length||plan.items.length>100)throw Error('Each packet needs 1–100 questions.');total+=plan.items.length;if(total>3000)throw Error('Generate at most 3,000 questions per batch.');const items=plan.items.map((i,n)=>{if(!known.has(i.sourceId))throw Error('Source preview cannot be exported: '+i.sourceId);if(!Number.isSafeInteger(i.index)||i.index<0)throw Error('Invalid variant index.');const seed=typeof i.seed==='string'?i.seed:s.seed;str(seed,200,'seed');if(!seed.trim())throw Error('Seed is required.');const q=E.generate(i.sourceId,{seed,index:i.index});return{number:n+1,sourceId:i.sourceId,seed,index:i.index,standard:known.get(i.sourceId).standard||null,q};});packets.push({name:plan.name,items});}return freeze({format:'studio-packet-session',version:1,engineVersion:E.version,mappingVersion:E.assessment.version,settings:s,packets});}
function manual(draft,value){const s=settings({...value,title:value?.title||draft.title,purpose:draft.purpose});if(!draft.itemIds.length)throw Error('Add questions to your draft first.');const unsupported=draft.itemIds.filter(id=>!known.has(id));if(unsupported.length)throw Error(unsupported.length+' source preview(s) cannot be exported. Remove them or choose Engine-ready questions: '+unsupported.slice(0,5).join(', '));if(draft.itemIds.length*s.count>100)throw Error('A packet can contain up to 100 questions. Reduce questions or variants per task.');return generate([{name:'',items:draft.itemIds.flatMap(sourceId=>Array.from({length:s.count},(_,n)=>({sourceId,index:(draft.generation.indices[sourceId]||0)+n,seed:s.seed})))}],s);}
function record(batch){return{format:batch.format,version:1,engineVersion:batch.engineVersion,mappingVersion:batch.mappingVersion,settings:clone(batch.settings),packets:batch.packets.map(p=>({name:p.name,items:p.items.map(({sourceId,seed,index})=>({sourceId,seed,index}))}))};}
function open(d){if(!d||d.format!=='studio-packet-session'||d.version!==1||d.engineVersion!==E.version||d.mappingVersion!==E.assessment.version)throw Error('This teacher session requires the same Engine and curriculum mapping version. Open it in its original Studio download.');return generate(d.packets,d.settings);}
const api={defaults,settings,importRows,score,csv,allocate,generate,manual,record,open};root.StudioPacketCore=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
