/* Local XLSX input and Word output; no remote calls. */
(function(root){'use strict';
const xml=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('Malformed workbook XML.');return d;},nodes=(n,t)=>Array.from(n.getElementsByTagNameNS('*',t)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
async function xlsx(buffer){if(buffer.byteLength>15000000)throw Error('Workbook is too large (15 MB limit).');const zip=await JSZip.loadAsync(buffer);let expanded=0;for(const f of Object.values(zip.files)){expanded+=f._data?.uncompressedSize||0;if(expanded>60000000)throw Error('Workbook expanded size exceeds 60 MB.');}async function part(p){const f=zip.file(p);if(!f)throw Error('Workbook is missing '+p);return xml(await f.async('string'));}
 const workbook=await part('xl/workbook.xml'),rels=await part('xl/_rels/workbook.xml.rels'),sheets=nodes(workbook,'sheet'),selected=sheets.filter(s=>s.getAttribute('name').trim()==='Student By Standard');if(selected.length!==1)throw Error('Select a workbook containing one sheet named Student By Standard.');const id=selected[0].getAttribute('r:id'),rel=nodes(rels,'Relationship').find(r=>r.getAttribute('Id')===id);if(!rel||rel.getAttribute('TargetMode')==='External')throw Error('External workbook sheets are not supported.');const target=rel.getAttribute('Target');let path=target.startsWith('/')?target.slice(1):'xl/'+target;if(path.includes('..')||!path.startsWith('xl/'))throw Error('Invalid sheet path.');
 const shared=zip.file('xl/sharedStrings.xml')?nodes(await part('xl/sharedStrings.xml'),'si').map(s=>nodes(s,'t').map(t=>t.textContent).join('')):[];const sheet=await part(path),rows=[];
 for(const row of nodes(sheet,'row')){const n=Number(row.getAttribute('r'));if(!Number.isInteger(n)||n<1||n>10000)throw Error('Workbook row limit exceeded.');const cells=[];for(const cell of nodes(row,'c')){const ref=cell.getAttribute('r')||'',match=/^([A-Z]+)\d+$/.exec(ref);if(!match)throw Error('Invalid cell address.');let col=0;for(const c of match[1])col=col*26+c.charCodeAt(0)-64;if(col>1200)throw Error('Workbook column limit exceeded.');const t=cell.getAttribute('t'),raw=nodes(cell,'v')[0]?.textContent;let v;if(t==='s'){v=shared[Number(raw)];if(v===undefined)throw Error('Invalid shared string.');}else if(t==='inlineStr')v=nodes(cell,'t').map(t=>t.textContent).join('');else if(t==='b')v=raw==='1';else if(t==='e')v='#ERROR';else if(raw!==undefined)v=t==='str'?raw:Number(raw);else v=null;cells[col-1]={v,f:nodes(cell,'f').length>0};}rows[n-1]=cells;}return Array.from({length:rows.length},(_,n)=>rows[n]||[]);
}
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',M='http://schemas.openxmlformats.org/officeDocument/2006/math';
function run(t,bold=false){return '<w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>'+(bold?'<w:b/>':'')+'</w:rPr><w:t xml:space="preserve">'+esc(t)+'</w:t></w:r>';}
function math(n){if(n.nodeType===3)return n.textContent.trim()?'<m:r><m:t>'+esc(n.textContent)+'</m:t></m:r>':'';const c=Array.from(n.childNodes),tag=n.localName;if(tag==='mfrac')return '<m:f><m:num>'+math(c[0])+'</m:num><m:den>'+math(c[1])+'</m:den></m:f>';if(tag==='msup')return '<m:sSup><m:e>'+math(c[0])+'</m:e><m:sup>'+math(c[1])+'</m:sup></m:sSup>';if(tag==='msub')return '<m:sSub><m:e>'+math(c[0])+'</m:e><m:sub>'+math(c[1])+'</m:sub></m:sSub>';if(tag==='msqrt')return '<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e>'+c.map(math).join('')+'</m:e></m:rad>';if(['mn','mi','mo','mtext'].includes(tag))return '<m:r><m:t xml:space="preserve">'+esc(n.textContent)+'</m:t></m:r>';return c.map(math).join('');}
function para(r,style=''){return '<w:p><w:pPr>'+(style.includes('<w:spacing')?'':'<w:spacing w:after="100"/>')+style+'</w:pPr>'+r+'</w:p>';}
async function docx(batch,mode){if(!['student','key','study'].includes(mode))throw Error('Choose an output type.');const zip=new JSZip(),s=batch.settings,rels=[],images=[];let imageId=0;const width=s.paper==='A4'?11906:12240,height=s.paper==='A4'?16838:15840,available=width-1440,columnWidth=(available-(s.columns-1)*360)/s.columns;
 async function image(svg){const vb=(svg.getAttribute('viewBox')||'0 0 400 240').split(/[ ,]+/).map(Number);const maxW=columnWidth/1440*96,maxH=mode==='student'?300:210,w=Math.min(maxW,480,maxH*vb[2]/vb[3]),h=w*vb[3]/vb[2];if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0)throw Error('Invalid diagram dimensions.');const copy=svg.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width',w*3);copy.setAttribute('height',h*3);copy.style.color='#111';const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'}));let png;try{const img=new Image();await new Promise((yes,no)=>{img.onload=yes;img.onerror=()=>no(Error('Diagram export failed. Your packet is preserved.'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=Math.ceil(w*3);canvas.height=Math.ceil(h*3);const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);png=canvas.toDataURL('image/png').split(',')[1];}finally{URL.revokeObjectURL(url);}const id=++imageId,cx=Math.round(w*9525),cy=Math.round(h*9525);zip.file('word/media/image'+id+'.png',png,{base64:true});rels.push('<Relationship Id="img'+id+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image'+id+'.png"/>');images.push(id);return '<w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'+cx+'" cy="'+cy+'"/><wp:docPr id="'+id+'" name="Question diagram" descr="'+esc(svg.getAttribute('aria-label')||'Mathematical diagram')+'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="diagram.png"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="img'+id+'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+cx+'" cy="'+cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>';}
 function inline(n,bold=false){if(n.nodeType===3)return run(n.textContent,bold);if(n.localName==='math')return '<m:oMath>'+math(n)+'</m:oMath>';if(n.localName==='br')return '<w:r><w:br/></w:r>';return Array.from(n.childNodes).map(c=>inline(c,bold||n.localName==='strong')).join('');}
 async function html(n){if(n.nodeType===3)return n.textContent.trim()?para(run(n.textContent),'<w:keepNext/>'):'';if(n.localName==='svg')return para(await image(n),'<w:keepNext/>');if(n.localName==='math')return para('<m:oMath>'+math(n)+'</m:oMath>','<w:keepNext/>');if(n.localName==='table'){const rows=Array.from(n.querySelectorAll('tr'));const count=Math.max(...rows.map(r=>r.children.length));let t='<w:tbl><w:tblPr><w:tblW w:w="'+columnWidth+'" w:type="dxa"/><w:tblBorders>'+['top','left','bottom','right','insideH','insideV'].map(x=>'<w:'+x+' w:val="single" w:sz="4" w:color="999999"/>').join('')+'</w:tblBorders><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid>'+Array.from({length:count},()=>'<w:gridCol w:w="'+Math.floor(columnWidth/count)+'"/>').join('')+'</w:tblGrid>';for(const row of rows){t+='<w:tr><w:trPr><w:cantSplit/></w:trPr>';for(const cell of row.children)t+='<w:tc><w:tcPr><w:tcW w:w="'+Math.floor(columnWidth/count)+'" w:type="dxa"/></w:tcPr>'+para(inline(cell,cell.localName==='th'),'<w:keepNext/>')+'</w:tc>';t+='</w:tr>';}return t+'</w:tbl>';}
 if(['p','li','h3','h4','figcaption'].includes(n.localName))return para(inline(n),'<w:keepNext/>');const parts=[];for(const c of n.childNodes)parts.push(await html(c));return parts.join('');}
 let body='';for(let pi=0;pi<batch.packets.length;pi++){const p=batch.packets[pi],footerId='footer'+(pi+1);body+=para(run(s.title,true),'<w:pStyle w:val="Title"/>'+(pi?'<w:pageBreakBefore/>':''));body+=para(run((mode==='student'?(s.purpose==='test'?'Test':'Practice'):mode==='key'?'Teacher key':'Study guide')+(p.name?' · '+p.name:'')));if(s.header)body+=para(run(s.header));if(mode==='student')body+=para(run((p.name?'':'Name ____________________   ')+'Date ____________________'));body+=para(run(s.instructions));
 // A section change gives Word real columns; each question remains an unbroken block where it fits.
 body+=para('', '<w:sectPr><w:footerReference w:type="default" r:id="'+footerId+'"/><w:type w:val="continuous"/><w:pgSz w:w="'+width+'" w:h="'+height+'"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/><w:cols w:num="1"/></w:sectPr>');
 for(const item of p.items){let question='';question+=para(run(String(item.number)+'.',true),'<w:keepNext/>');const div=document.createElement('div');div.innerHTML=MathEngineBanks.renderQuestion(item.q);question+=await html(div);if(mode!=='student'){question+=para(run('Answer: '+MathEngineBanks.answerText(item.q),true),'<w:keepNext/>');question+=para(run(item.q.solution||''),'<w:keepNext/>');if(item.q.teacherSvg){const d=document.createElement('div');d.innerHTML=item.q.teacherSvg;question+=await html(d);}question+=para(run((item.standard?'Outcome: '+item.standard:'Task: '+MathEngineBanks.catalog.find(c=>c.sourceId===item.sourceId).title)+' · variant '+item.index));}else question+=para(run(' '),'<w:spacing w:after="0" w:line="'+Math.max(20,Math.round(s.space*56.693))+'" w:lineRule="exact"/>');if(s.dividers)question+=para('', '<w:pBdr><w:bottom w:val="single" w:sz="4" w:color="CCCCCC"/></w:pBdr>');body+='<w:tbl><w:tblPr><w:tblW w:w="'+columnWidth+'" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="0" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="'+columnWidth+'"/></w:tblGrid><w:tr><w:trPr><w:cantSplit/></w:trPr><w:tc><w:tcPr><w:tcW w:w="'+columnWidth+'" w:type="dxa"/></w:tcPr>'+question+'</w:tc></w:tr></w:tbl>'+para('','<w:spacing w:after="0" w:line="20" w:lineRule="exact"/>');}
 if(pi<batch.packets.length-1)body+=para('','<w:sectPr><w:footerReference w:type="default" r:id="'+footerId+'"/><w:type w:val="continuous"/><w:pgSz w:w="'+width+'" w:h="'+height+'"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/><w:cols w:num="'+s.columns+'" w:space="360"/></w:sectPr>');}
 const ns='xmlns:w="'+W+'" xmlns:m="'+M+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"';
 body+='<w:sectPr><w:type w:val="continuous"/><w:footerReference w:type="default" r:id="footer'+batch.packets.length+'"/><w:pgSz w:w="'+width+'" w:h="'+height+'"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:footer="300"/><w:cols w:num="'+s.columns+'" w:space="360"/></w:sectPr>';
 zip.file('word/document.xml','<?xml version="1.0" encoding="UTF-8"?><w:document '+ns+'><w:body>'+body+'</w:body></w:document>');
 batch.packets.forEach((p,n)=>{zip.file('word/footer'+(n+1)+'.xml','<w:ftr '+ns+'>'+para(run((p.name?p.name+' · ':'')+s.footer+'  ·  ')+ '<w:fldSimple w:instr="PAGE"/>')+'</w:ftr>');rels.push('<Relationship Id="footer'+(n+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer'+(n+1)+'.xml"/>');});
 zip.file('word/settings.xml','<w:settings xmlns:w="'+W+'"><w:compat><w:doNotBalanceTextColumns/></w:compat></w:settings>');
 zip.file('word/styles.xml','<w:styles xmlns:w="'+W+'"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style></w:styles>');
 zip.file('word/_rels/document.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+rels.join('')+'<Relationship Id="settings" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
 zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="document" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
 zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>'+batch.packets.map((_,n)=>'<Override PartName="/word/footer'+(n+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>').join('')+'</Types>');
 return zip.generateAsync({type:'blob',compression:'DEFLATE',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
}
root.StudioPacketIO={xlsx,docx};
})(globalThis);
