/* Shared validated format contract for preview, Word and saved sessions. */
(function(root){'use strict';
const defaults={marginTop:12,marginBottom:12,marginLeft:12,marginRight:12,mirrorMargins:false,columnGap:8,verticalDivider:false,fontFamily:'Arial',fontSize:11,lineSpacing:1.35,paragraphSpacing:2,questionSpacing:3,answerBlank:'none',answerBlankWidth:35,distractors:'auto',keepTogether:true,instructionsPlacement:'every',headerFirst:'',headerOdd:'',headerEven:'',footerFirst:'',footerOdd:'',footerEven:'',headerTarget:'all',footerTarget:'all',headerRule:'none',footerRule:'above',studentNameHeader:true};
const numeric={marginTop:[6,40],marginBottom:[6,40],marginLeft:[6,40],marginRight:[6,40],columnGap:[3,20],fontSize:[9,18],lineSpacing:[1,2],paragraphSpacing:[0,8],questionSpacing:[0,15],answerBlankWidth:[10,70]};const enums={fontFamily:['Arial','Calibri','Times New Roman'],answerBlank:['none','below','beside','separate'],distractors:['auto','vertical','horizontal'],instructionsPlacement:['every','first','questions'],headerTarget:['all','student','key','study'],footerTarget:['all','student','key','study'],headerRule:['none','above','below','both'],footerRule:['none','above','below','both']};
function text(v,max=500){if(typeof v!=='string'||v.length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v))throw Error('Invalid formatting text.');return v;}
function validate(value){const s={...defaults,...value};for(const [k,[lo,hi]]of Object.entries(numeric))if(!Number.isFinite(s[k])||s[k]<lo||s[k]>hi)throw Error(k+' must be between '+lo+' and '+hi+'.');for(const[k,allowed]of Object.entries(enums))if(!allowed.includes(s[k]))throw Error('Invalid '+k+'.');for(const k of ['mirrorMargins','verticalDivider','keepTogether','studentNameHeader'])if(typeof s[k]!=='boolean')throw Error('Invalid '+k+'.');for(const k of ['headerFirst','headerOdd','headerEven','footerFirst','footerOdd','footerEven'])text(s[k],160);return s;}
function item(value={}){if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid question layout.');const d={space:null,annotation:'',breakBefore:'none',keepWithNext:false,section:null,...value};if(Object.keys(d).some(k=>!['space','annotation','breakBefore','keepWithNext','section'].includes(k)))throw Error('Unsupported question layout.');if(d.space!==null&&(!Number.isInteger(d.space)||d.space<0||d.space>80))throw Error('Question space must be 0–80 mm.');text(d.annotation,500);if(!['none','page','column','optional'].includes(d.breakBefore)||typeof d.keepWithNext!=='boolean')throw Error('Invalid break or keep setting.');if(d.section!==null){if(typeof d.section!=='object'||Array.isArray(d.section)||Object.keys(d.section).some(k=>!['title','header','footer','columns'].includes(k)))throw Error('Invalid section.');d.section={title:'',header:'',footer:'',columns:1,...d.section};for(const k of ['title','header','footer'])text(d.section[k],160);if(![1,2].includes(d.section.columns))throw Error('Invalid section columns.');}return d;}
function sections(packet,s){const result=[];let current;for(const q of packet.items){const f=item(q.layout);if(!current||f.section){const change=f.section||{};current={settings:{...s,...(f.section?{columns:change.columns,header:change.header||s.header,footer:change.footer||s.footer,headerFirst:change.header?'':s.headerFirst,headerOdd:change.header?'':s.headerOdd,headerEven:change.header?'':s.headerEven,footerFirst:change.footer?'':s.footerFirst,footerOdd:change.footer?'':s.footerOdd,footerEven:change.footer?'':s.footerEven}:{})},title:change.title||'',items:[]};result.push(current);}current.items.push({...q,layout:f});}return result;}
function tokens(t,p,s,page){return t.replace(/\{(student|title|course|page)\}/g,(_,k)=>({student:p.name||'',title:s.title,course:p.courseLabel||'',page:String(page)})[k]);}
function band(s,part,p,mode,page,first){if(s[part+'Target']!=='all'&&s[part+'Target']!==mode)return'';const chosen=(first?s[part+'First']:'')||s[part+(page%2?'Odd':'Even')]||s[part]||'';return tokens(chosen,p,s,page);}
const api={defaults,numeric,enums,validate,item,sections,tokens,band};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.StudioPacketFormat=api;
})(globalThis);
