(function(root){'use strict';
const C=StudioPacketCore,E=MathEngineBanks,$=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const printCSS=`*{box-sizing:border-box}body{margin:0;background:#e5e8ec;color:#111;font:11pt Arial,sans-serif}.sheet{background:white;margin:16px auto;padding:12mm;width:210mm;height:297mm;display:flex;flex-direction:column;overflow:hidden}.sheet.letter{width:215.9mm;height:279.4mm}.sheet h1{font-size:18pt;margin:0 0 3mm}.sheet-head{flex:none;padding-bottom:4mm}.sheet-head p{margin:2mm 0;font-size:10pt;white-space:pre-wrap;overflow-wrap:anywhere}.sheet-body{display:flex;gap:8mm;flex:1;min-height:0}.sheet-column{flex:1;min-width:0}.packet-question{padding:2mm 0 3mm;break-inside:avoid;overflow-wrap:anywhere}.packet-question.divider{border-bottom:1px solid #b8c1c4;margin-bottom:3mm}.packet-question p{margin:2mm 0;line-height:1.35}.packet-question svg{display:block;width:100%;max-width:125mm;height:auto;max-height:80mm;object-fit:contain;margin:2mm auto}.packet-question math{font-size:13pt;max-width:100%;margin:2mm 0}.packet-question table{border-collapse:collapse;max-width:100%;font-size:10pt}.packet-question td,.packet-question th{padding:2mm;border:1px solid #888}.question-number{font-weight:bold}.work-space{height:30mm}.answer{font-weight:bold}.source-label{font-size:8pt;color:#555}.sheet-foot{flex:none;padding-top:3mm;margin-top:3mm;border-top:1px solid #ddd;font-size:8pt;display:flex;justify-content:space-between;gap:5mm;overflow-wrap:anywhere}.sheet-foot span:first-child{max-width:75%}@media print{body{background:white}.sheet{margin:0;break-after:page}.sheet:last-child{break-after:auto}@page{size:A4;margin:0}}`;
function article(item,s,mode,doc){const a=doc.createElement('article');a.className='packet-question'+(s.dividers?' divider':'');a.dataset.number=item.number;a.innerHTML='<div class="question-number">'+item.number+'.</div>'+E.renderQuestion(item.q);if(mode==='student'){const space=doc.createElement('div');space.className='work-space';space.style.height=s.space+'mm';a.append(space);}else{const ans=doc.createElement('p');ans.className='answer';ans.textContent='Answer: '+E.answerText(item.q);a.append(ans);const solution=doc.createElement('p');solution.textContent=item.q.solution||'';a.append(solution);if(item.q.teacherSvg){const d=doc.createElement('div');d.innerHTML=item.q.teacherSvg;a.append(d);}const source=doc.createElement('p');source.className='source-label';source.textContent=(item.standard||item.sourceId)+' · variant '+item.index;a.append(source);}return a;}
async function layout(doc,batch,mode){if(!['student','key','study'].includes(mode))throw Error('Unknown output mode.');const s=batch.settings;doc.open();doc.write('<!doctype html><html><head><meta charset="utf-8"><title>'+escape(s.title)+' · '+mode+' · Studio v'+StudioCore.VERSION+'</title><style>'+printCSS+(s.paper==='Letter'?'@media print{@page{size:Letter}}':'')+'</style></head><body></body></html>');doc.close();await doc.fonts.ready;
 const pages=[];for(const packet of batch.packets){let sheet,columns,col=0;function nextPage(){sheet=doc.createElement('section');sheet.className='sheet'+(s.paper==='Letter'?' letter':'');const head=doc.createElement('div');head.className='sheet-head';head.innerHTML='<h1>'+escape(s.title)+'</h1><p>'+escape(mode==='student'?(s.purpose==='test'?'Test':'Practice'):mode==='key'?'Teacher key':'Study guide')+(packet.name?' · '+escape(packet.name):'')+'</p>'+(s.header?'<p>'+escape(s.header)+'</p>':'')+(mode==='student'?'<p>'+(packet.name?'':'Name ____________________   ')+'Date ____________________</p>':'')+'<p>'+escape(s.instructions)+'</p>';const body=doc.createElement('div');body.className='sheet-body';columns=Array.from({length:s.columns},()=>{const n=doc.createElement('div');n.className='sheet-column';body.append(n);return n;});const foot=doc.createElement('div');foot.className='sheet-foot';foot.innerHTML='<span>'+escape(s.footer)+'</span><span class="page-number"></span>';sheet.append(head,body,foot);doc.body.append(sheet);pages.push(sheet);col=0;return body;}
 let body=nextPage();for(const item of packet.items){const a=article(item,s,mode,doc);columns[col].append(a);if(columns[col].scrollHeight>body.clientHeight+1){a.remove();if(col+1<s.columns)col++;else body=nextPage();columns[col].append(a);if(columns[col].scrollHeight>body.clientHeight+1)throw Error('Question '+item.number+' is too tall for this layout. Choose one column, less work space or shorter instructions.');}if(a.scrollWidth>a.clientWidth+2)throw Error('Question '+item.number+' is too wide. Choose one column.');}}
 pages.forEach((p,n)=>p.querySelector('.page-number').textContent='Page '+(n+1)+' of '+pages.length);return pages.length;
}
function mount({getDraft}){
 let imported=null,plans=null,batch=null,undo=null,unsaved=false,renderToken=0;const host=$('packet-tools');host.innerHTML=`<div class="sectionhead"><div><p class="eyebrow">04 / PRODUCE</p><h2>Packets and teacher keys</h2></div><span class="pill">Local processing</span></div>
<p>Build from your manual draft, or use a Grade 5 GradeCam export to review individual practice needs. Download your teacher session before closing.</p>
<div class="packet-settings"><label>Packet title<input id="packet-title" maxlength="120" value="Introduction to PreAlgebra practice"></label><label>Header<input id="packet-header" maxlength="160" placeholder="Class or assessment information"></label><label>Student instructions<textarea id="packet-instructions" maxlength="500">Show your work. Write each answer clearly.</textarea></label><label>Footer<input id="packet-footer" maxlength="160"></label><label>Seed<input id="packet-seed" value="practice" maxlength="200"></label><label>Variants per task<input id="packet-count" type="number" min="1" max="10" value="2"></label><label>Paper<select id="packet-paper"><option>A4</option><option>Letter</option></select></label><label>Columns<select id="packet-columns"><option value="1">One</option><option value="2">Two</option></select></label><label>Work space per question (mm)<input id="packet-space" type="number" min="0" max="80" value="30"></label><label><input id="packet-dividers" type="checkbox"> Question dividers</label></div>
<details class="help wide"><summary>How do packet settings work?</summary><p>The seed and variant index reproduce questions with this Engine version. Settings apply when you build a packet; existing packets remain unchanged. One column is recommended for diagrams. Work space applies to student sheets. Keys include answers and teacher review criteria; study guides include questions with their solutions. Use your browser’s Print / Save as PDF with matching paper size and no browser headers or footers.</p></details><button id="packet-manual">Build packet from manual draft</button>
<details class="targeting"><summary>GradeCam targeting · Grade 5 only</summary><p>Import Student By Standard. Scores are aggregate evidence, not a mastery diagnosis. No student information leaves this page. Other grades remain available in manual bank selection.</p><div class="packet-settings"><label>Numeric score scale<select id="score-scale"><option value="proportion">0–1 proportions (GradeCam XLSX default)</option><option value="percent">0–100 percentages</option></select></label><label>GradeCam file<input id="gradecam-file" type="file" accept=".xlsx,.csv"></label><label>Target scores below (%)<input id="target-threshold" type="number" min="0" max="100" value="70"></label><label>Maximum questions per student<input id="packet-cap" type="number" min="1" max="100" value="40"></label><label><input id="target-missing" type="checkbox"> Include blank / hyphen evidence</label></div><p class="muted">Set the numeric scale before importing. Percentage strings such as 70% work with either scale. Blank and hyphen cells stay separate from zero. Changing the scale requires reimporting the file.</p><div class="actions"><button id="target-all" disabled>Select all students</button><button id="target-none" disabled>Clear student selection</button><button id="target-unload" disabled>Clear imported class</button><button id="target-undo" disabled>Undo import change</button></div><div id="target-summary"></div><div class="target-grids"><div><h3>Students</h3><div id="target-students"></div></div><div><h3>Standards</h3><div id="target-standards"></div></div></div><label id="unknown-review" hidden><input id="unknown-ack" type="checkbox"> I reviewed the unknown codes below and will exclude them.</label><div id="target-unknown"></div><button id="target-review" disabled>Review allocations</button><div id="target-plan"></div><button id="target-build" disabled>Build reviewed student packets</button></details>
<div id="packet-status" role="status" aria-live="polite"></div><div class="actions packet-actions"><label class="filebutton">Open teacher session<input id="packet-open" type="file" accept=".json"></label><button id="packet-save" disabled>Download teacher session</button><button id="packet-clear" disabled>Clear all packets</button><button id="packet-undo" disabled>Undo packet change</button></div><p class="muted">Teacher session files contain learner names and reproducible questions and keys. Keep them private. Student exports contain only the selected student output. No automatic browser storage; clearing this page does not delete downloaded files.</p><div id="packet-list"></div><div class="packet-settings"><label>Preview and export<select id="packet-mode"><option value="student">Student worksheet</option><option value="key">Teacher key</option><option value="study">Study guide with solutions</option></select></label><label>Packet<select id="packet-choice"><option value="all">Entire batch</option></select></label></div><div class="actions"><button id="packet-preview" disabled>Refresh preview</button><button id="packet-print" disabled>Print / Save as PDF</button><button id="packet-word" disabled>Download Word document</button></div><p id="packet-preview-note" class="muted"></p><iframe id="packet-frame" title="Packet output preview"></iframe>`;
 function message(t,error=false){$('packet-status').textContent=t;$('packet-status').className=error?'error':'';}
 function readSettings(){return C.settings({title:$('packet-title').value,header:$('packet-header').value,instructions:$('packet-instructions').value,footer:$('packet-footer').value,paper:$('packet-paper').value,columns:Number($('packet-columns').value),space:Number($('packet-space').value),dividers:$('packet-dividers').checked,count:Number($('packet-count').value),cap:Number($('packet-cap').value),seed:$('packet-seed').value,purpose:getDraft().purpose});}
 function sync(s){for(const key of ['title','header','instructions','footer','paper','columns','space','count','cap','seed'])$('packet-'+key).value=s[key];$('packet-dividers').checked=s.dividers;}
 function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function visibleBatch(){if(!batch)throw Error('Build a packet first.');const chosen=$('packet-choice').value;if(chosen==='all')return batch;const p=batch.packets[Number(chosen)];if(!p)throw Error('Choose an available packet.');return{...batch,packets:[p]};}
 function invalidate(){plans=null;$('target-build').disabled=true;$('target-plan').replaceChildren();}
 function checkbox(label,value,checked=true){const l=el('label'),c=el('input');c.type='checkbox';c.value=value;c.checked=checked;c.onchange=invalidate;l.append(c,document.createTextNode(' '+label));return l;}
 function targetDisplay(){invalidate();for(const id of ['target-students','target-standards','target-unknown'])$(id).replaceChildren();for(const id of ['target-all','target-none','target-unload','target-review'])$(id).disabled=!imported;$('target-summary').textContent=imported?imported.students.length+' students · '+imported.columns.filter(c=>c.sourceId).length+' mapped outcomes · numeric scale: '+imported.scale:'';$('unknown-review').hidden=true;$('unknown-ack').checked=false;if(!imported)return;
 for(const st of imported.students){const row=el('div');row.append(checkbox(st.name,st.key));const b=el('button','Remove');b.onclick=()=>{if(confirm('Remove '+st.name+' from this imported class? Undo is available until the next import change.')){targetUndo=imported;imported={...imported,students:imported.students.filter(x=>x.key!==st.key)};targetDisplay();$('target-undo').disabled=false;}};row.append(b);$('target-students').append(row);}for(const col of imported.columns){if(col.sourceId)$('target-standards').append(checkbox(col.raw+(col.raw!==col.standard?' → '+col.standard:''),col.raw));else{$('unknown-review').hidden=false;$('target-unknown').append(el('p','Excluded unknown/out-of-scope code: '+col.raw));}}
 }
 let targetUndo=null;
 async function preview(){const token=++renderToken;$('packet-print').disabled=true;$('packet-word').disabled=true;try{const n=await layout($('packet-frame').contentDocument,visibleBatch(),$('packet-mode').value);if(token!==renderToken)return;$('packet-preview-note').textContent=n+' pages · '+($('packet-mode').value==='student'?'Student output — no teacher answers.':'Contains answers. For teachers or intentional study guides.')+' · Saved packet settings; rebuild to apply edited controls.';$('packet-print').disabled=false;$('packet-word').disabled=false;}catch(e){message(e.message,true);$('packet-frame').contentDocument.body.replaceChildren();}}
 function renderBatch(){for(const id of ['packet-save','packet-clear','packet-preview'])$(id).disabled=!batch;$('packet-undo').disabled=!undo;$('packet-list').replaceChildren();$('packet-choice').replaceChildren(new Option('Entire batch','all'));if(batch){batch.packets.forEach((p,n)=>{const row=el('div');row.append(el('span',(p.name||'Manual packet')+' · '+p.items.length+' questions '));const b=el('button','Remove');b.onclick=()=>{if(confirm('Remove this packet of '+p.items.length+' questions? Undo is available.'))setBatch(batch.packets.length===1?null:{...batch,packets:batch.packets.filter((_,j)=>j!==n)});};row.append(b);$('packet-list').append(row);$('packet-choice').append(new Option(p.name||'Manual packet',String(n)));});preview();}else{$('packet-frame').contentDocument.body?.replaceChildren();$('packet-print').disabled=true;$('packet-word').disabled=true;$('packet-preview-note').textContent='';}}
 function setBatch(next){undo=batch;batch=next;unsaved=true;renderBatch();}
 const attempt=fn=>async()=>{try{await fn();}catch(e){message(e.message,true);}};
 $('packet-manual').onclick=attempt(()=>{const next=C.manual(getDraft(),readSettings());setBatch(next);message('Built '+next.packets[0].items.length+' questions. Preview student output and teacher key before exporting.');});
 $('gradecam-file').onchange=attempt(async()=>{const f=$('gradecam-file').files[0];if(!f)return;try{if(f.size>15000000)throw Error('Choose a file smaller than 15 MB.');const rows=f.name.toLowerCase().endsWith('.csv')?C.csv(await f.text()):await StudioPacketIO.xlsx(await f.arrayBuffer()),next=C.importRows(rows,$('score-scale').value);if(imported&&!confirm('Replace the imported class of '+imported.students.length+' students? Undo is available.'))return;targetUndo=imported;imported=next;unsaved=true;targetDisplay();$('target-undo').disabled=!targetUndo;message('Imported locally. Review students and standards before allocating questions.');}finally{$('gradecam-file').value='';}});
 $('target-all').onclick=()=>{document.querySelectorAll('#target-students input').forEach(c=>c.checked=true);invalidate();};$('target-none').onclick=()=>{document.querySelectorAll('#target-students input').forEach(c=>c.checked=false);invalidate();};$('target-unload').onclick=()=>{if(confirm('Clear this imported class of '+imported.students.length+' students and its scores? Generated packets and downloaded files remain. Undo is available.')){targetUndo=imported;imported=null;targetDisplay();$('target-undo').disabled=false;}};$('target-undo').onclick=()=>{const current=imported;imported=targetUndo;targetUndo=current;targetDisplay();$('target-undo').disabled=!targetUndo;};
 for(const id of ['target-threshold','target-missing','packet-cap','unknown-ack','score-scale'])$(id).onchange=invalidate;for(const n of host.querySelectorAll('.packet-settings input,.packet-settings textarea,.packet-settings select'))n.addEventListener('change',invalidate);
 $('target-review').onclick=attempt(()=>{if(!imported)throw Error('Import a class first.');if(imported.columns.some(c=>!c.sourceId)&&!$('unknown-ack').checked)throw Error('Review and acknowledge excluded unknown codes first.');const options={threshold:Number($('target-threshold').value),includeMissing:$('target-missing').checked,students:[...document.querySelectorAll('#target-students input:checked')].map(c=>c.value),standards:[...document.querySelectorAll('#target-standards input:checked')].map(c=>c.value),settings:readSettings()};plans=C.allocate(imported,options);if(!plans.length)throw Error('Select at least one student.');$('target-plan').replaceChildren();for(const plan of plans){const details=el('details'),sum=el('summary',plan.name+': '+plan.items.length+' questions'+(plan.omitted?' · '+plan.omitted+' omitted by cap':''));details.append(sum);const groups=new Map();for(const it of plan.items)groups.set(it.importedCode,(groups.get(it.importedCode)||0)+1);for(const [code,n]of groups)details.append(el('p',code+' · '+n+' questions'));if(!plan.items.length)details.append(el('p','No selected evidence met the rule. No packet will be generated.'));const ids=[...new Set(plan.items.map(i=>i.sourceId))],pairs=E.assessment.overlaps(ids);if(pairs.length)details.append(el('p',pairs.length+' overlapping outcome pair(s). Scores stay separate; all requested outcomes are retained. Uncheck a standard above if you do not want repeated coverage.'));$('target-plan').append(details);}$('target-build').disabled=!plans.some(p=>p.items.length);message('Review allocations above, including capped or empty packets.');});
 $('target-build').onclick=attempt(()=>{if(!plans)throw Error('Review allocations after changing settings.');const s=readSettings(),next=C.generate(plans.filter(p=>p.items.length),s);setBatch(next);message('Built '+next.packets.length+' student packets. Imported scores remain separate from the generated packet session.');});
 $('packet-save').onclick=()=>{download(new Blob([JSON.stringify({...C.record(batch),appVersion:StudioCore.VERSION},null,2)],{type:'application/json'}),'Studio-Teacher-Session-v'+StudioCore.VERSION+'.json');unsaved=false;message('Teacher session downloaded. Keep it private; it can reproduce the student questions and teacher keys. Imported score tables are not included.');};
 $('packet-open').onchange=attempt(async()=>{const f=$('packet-open').files[0];if(!f)return;try{if(f.size>5000000)throw Error('Teacher session file is too large.');const next=C.open(JSON.parse(await f.text()));if(batch&&!confirm('Replace all '+batch.packets.length+' current packets? Undo is available.'))return;setBatch(next);sync(next.settings);message('Teacher session reopened using its pinned Engine version.');}finally{$('packet-open').value='';}});
 $('packet-clear').onclick=()=>{if(confirm('Clear all '+batch.packets.length+' packets? Imported scores, manual draft and downloaded files remain. Undo is available.'))setBatch(null);};$('packet-undo').onclick=()=>{if(!undo)return;const temp=batch;batch=undo;undo=temp;unsaved=true;renderBatch();};
 $('packet-preview').onclick=preview;$('packet-mode').onchange=()=>{if(batch)preview();};$('packet-choice').onchange=()=>{if(batch)preview();};$('packet-print').onclick=()=>{const w=$('packet-frame').contentWindow;w.focus();w.print();};$('packet-word').onclick=attempt(async()=>{const output=visibleBatch(),mode=$('packet-mode').value;$('packet-word').disabled=true;try{const blob=await StudioPacketIO.docx(output,mode);download(blob,'Studio-'+mode+'-v'+StudioCore.VERSION+'.docx');message('Word document downloaded. The saved teacher session preserves these exact question variants.');}finally{$('packet-word').disabled=false;}});
 window.addEventListener('beforeunload',e=>{if(unsaved&&(imported||batch)){e.preventDefault();e.returnValue='';}});
}
root.StudioPackets={mount,layout};
})(globalThis);
